### ISSUE TITLE
Pupil Player - estimate detected surface `X size` and `Y size` from video

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#101]
Migrated from #96 -- @cpicanco's idea of setting an estimated default surface size for defined surfaces based on what is observed in the video. This may lead to better immediate visualizations within player (and less confusion for users). A simple average of the surface size (in screen coordinates) could be used. 

Cons - this method would result in poor estimations when the surface is always highly skewed in the video. The size of the markers could be used to compensate for the case of the always skewed surface -- and surface rectified to get sane values. However the amount of work might be overkill for this issue.

**Comment by mkassner** [comment]
Unfortunately this is not possible. 

The only way to determine the surface size would be by looking at the markers that support it.

By design the marker size is variable.This is good because you can use and mix small and bigger markers. But this also means that we (the program) has no knowledge if we are looking at the close small or distant big surface. This is why the user has to supply the size in the UI.

The only thing that could be estimated is the aspect ration but again I would say if the user is forced to supply the size, the aspect ratio is taken care of at the same time.

So the best way to deal with this is to add instructions in the UI as @willpatera has already done.

**Comment by cpicanco** [comment]
Hi @mkassner and @willpatera, if I understand it correctly, the program by design delegates to the human eye the estimation of the x_size and y_size. I will check your instructions :)

**Comment by cpicanco** [comment]
@mkassner, It would be possible to estimate the x_size and y_size from edited surfaces? Indeed, an edited surface is an human eye estimation.
