### ISSUE TITLE
Problems using Logitech C525

### ISSUE THREAD

**Issue by gmierz** [pupil-labs/pupil#1098]
Currently, you suggest to use a logitech C525 as the world camera in you DIY parts list: https://docs.google.com/spreadsheets/d/1NRv2WixyXNINiq1WQQVs5upn20jakKyEl1R8NObrTgU/pub?single=true&gid=0&output=html

I have gotten one, installed the libusbK drivers on it, and it gives me the error: "The selected camera is already in use or blocked."

There are also countless issues that were closed without being resolved for this camera, and for the same error. So, you shouldn't be suggesting it to people if it doesn't work with your setup.

Is there any that work well, or are suggested, on Windows?

**Comment by cpicanco** [comment]
@gmierz welcome to the Pupil Community. I am sorry if you are having a bad time with your setup. I would like to say some words and please don't get me wrong, it is for your own good.

As mentioned in the docs (https://docs.pupil-labs.com/#diy), Pupil Dev is for makers, hackers, uber nerds. Also, it should be noted that Pupil Software is optimized for Pupil cameras. Because Pupil Software is open-source it is implicit that one should be prepared to understand, adapt, fix, maintain his/her own code/hardware. It would be great if Pupil already worked with all machines and all cameras. As you can see, it is not the case. If you think something is missing at the docs you are welcomed to make a pull request with your suggestions.

That said, issue #831 demonstrates that error "The selected camera is already in use or blocked" can occur in GNU/Linux systems as well (with Logitech C615 and others). Because I have tested this cameras in different machines, I can tell you that C525 and C615 should work out of the box in machines that have two separated USB controllers. For example, I have an intel desktop with two USB 3.0 controllers and I can garantee that C525 and C615 and others worked out-of-the-box.

Can you confirm if your machine have two USB controllers?

**Comment by gmierz** [comment]
@cpicanco thanks a lot for the help - sorry if I was rude.

Thanks, I would have never guessed that it depended on the number of USB controllers. If I had a Pupil Labs world camera - as an addition to the Pupil Labs eye cameras - would I still need multiple USB controllers? 

You're right, I only had one controller. But I just tried it on a computer with multiple controllers and I get the same issue. I'm wondering if I messed up the libusbK driver installation [here]. Which whell file do you use? I am using [v0.11].

[here]: https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md
[v0.11]: https://github.com/pupil-labs/pyuvc/releases/tag/v0.11

**Comment by cpicanco** [comment]
Nice!

**Comment by cpicanco** [comment]
USB controllers are the recommended setup. For machines with single controllers, another path would be to tackle USB bandwidth parameters in the source code. I am afraid I could not help with that.
