### ISSUE TITLE
200 Hz Camera Issue

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#1116]
Hi there,

sometimes we experience image issues with 200Hz Cameras:

![screenshot from 2018-03-12 14-01-20](https://user-images.githubusercontent.com/10213803/37292967-5cb04798-2612-11e8-9889-c047b15e8f0c.png)

Often those stripes vanish by changing resolution and frame rate and changing back to 192x192 + 200Hz. On lower frequencies the vertical stripes don't appear. Sometimes deleting pupil capture settings or restarting the software helps to remove the stripes.

What could be the reason for that graphical issue?

**Comment by papr** [comment]
We have encountered this issue as well a few times but are not able to reproduce it yet. Reactivating the camera in the uvc manager or restarting the eye process solved the issue in our cases. Please let us know if these steps are not sufficient to solve the issue temporally. This would indicate that the issue is persistent through multiple uvc connection sessions (if you can call them that)...

**Comment by mkassner** [comment]
@fneitzel this does very rarely happen with the 200hz cameras. Simply re-applying the frame-rate or restarting the eye window will resolve the issue. If you have individual cameras where this happens more frequently contact us and we will do a replacement.
