### ISSUE TITLE
Right menu in pupil capture has disappeared

### ISSUE THREAD

**Issue by PatrycjaPAKS** [pupil-labs/pupil#1117]
Hey,

We're currently running a pupillometry experiment with your PupilLabs camera. Today, we've experienced a problem with the right menu. After clicking twice one of the icons, the menu has disappeared and we are not able to see the settings anymore. Screenshot is below:
![failmenu](https://user-images.githubusercontent.com/30791911/37347147-731d9f02-26d1-11e8-8a15-3756e9c5ccdf.PNG)
Despite of clicking the menu buttons, menu doesn't show up unfortunately. The logging screen from starting the application is:
![failmenu_log](https://user-images.githubusercontent.com/30791911/37347241-abdee8dc-26d1-11e8-8272-c51e0f834231.PNG)

Is there any quick fix we could use to make the menu appear again (tomorrow we have a next visit, so help is urgent in this case)? We're using pupil capture v. 1.2 as this was the one available while we were preparing the test. Since it's the students who run an experiment, we would like to keep this version of the software if possible.

Looking forward to hearing from you.

Patrycja

**Comment by papr** [comment]
Dear Patrycja,
this is a known bug for that version. It has been fixed in more recent releases.

A temporary fix is to delete the session settings:
1. Shut down Capture
2. Delete the `user_settings_...` files in your `pupil_capture_settings` folder which you can find in the users home folder.
3. Start Capture

This will reset all user settings and will not prevent this bug from happening. The long term solution is to upgrade your software to the newest version.
