### ISSUE TITLE
Catch except when disk space is full & end file gracefully

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1201]
It sometimes happen (especially if recording eye videos) that diskspace is running out.

currently pupillabs simply crashes and some data is lost (timestamps.py, pupil-data with notifications etc.). It would be nice to catch that exception and try to quit gracefully (or at least halt the program, so that diskspace can be freed to end the programm gracefully)

**Comment by emolyzr** [comment]
... or give out a warning when disk space is running low.

**Comment by behinger** [comment]
I feel a warning is not sufficient. We have 80gbyte recordings, thus where to put the threshold to push the warning?
What about recorsings started from zmq?
I feel catvhing the error and wait for user input better

Am 29. Mai 2018 18:46:17 MESZ schrieb emolyzr <notifications@github.com>:

**Comment by emolyzr** [comment]
I understand your point. However, holding the program or quitting gracefully effectively means: (some) data gets lost. Getting a warning gives you, the operator, some time to free disk space. The threshold can be set individually via the GUI.
After all the safest way is to do your recordings and immediately transfer them to an external hard disk or server thereafter. So that there's always enough space on your smaller disk (SSD, I suppose). If you include this into your workflow, nothing should go wrong.

**Comment by behinger** [comment]
I imagine a plugin is super easy to write to get such a warning (just import sys, get the sys diskfree of the recording folder and check against a threshold).

Of course transfering the data after an experiment would be the best thing :-) But you know, accidents happen - multiple users use the same lab computers etc..

still think it could be possible to catch the exception and halt the process. Why not have the best of both worlds?

**Comment by papr** [comment]
The problem with the exception is that there is no space left to write any data to the disk. We should check for a threshold and stop the recording early enough.

**Comment by emolyzr** [comment]
Best of Both: 
> give a warning at thresh 1
and
> stop at thresh 2 

;)
