### ISSUE TITLE
fatal error C1007: unrecognized flag '-Ot' in 'p2'

### ISSUE THREAD

**Issue by cconst04** [pupil-labs/pupil#1208]
`EyeModel.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Users\Chris\Desktop\ucy\DMAC internship\Pupil-labs\work\boost\stage\lib" /LIBPATH:C:\Users\Chris\AppData\Local\Programs\Python\Python36\libs /LIBPATH:C:\Users\Chris\AppData\Local\Programs\Python\Python36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26428\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x86" /EXPORT:PyInit_detector_3d build\temp.win-amd64-3.6\Release\detector_3d.obj build\temp.win-amd64-3.6\Release\singleeyefitter/ImageProcessing/cvx.obj build\temp.win-amd64-3.6\Release\singleeyefitter/utils.obj build\temp.win-amd64-3.6\Release\singleeyefitter/detectorUtils.obj build\temp.win-amd64-3.6\Release\singleeyefitter/EyeModelFitter.obj build\temp.win-amd64-3.6\Release\singleeyefitter/EyeModel.obj  "C:\Users\Chris\Desktop\ucy\DMAC internship\Pupil-labs\work\opencv\build\x64\vc14\lib\opencv_world320.lib"  "C:\Users\Chris\Desktop\ucy\DMAC internship\Pupil-labs\work\ceres-windows\x64\Release\ceres_static.lib" "C:\Users\Chris\Desktop\ucy\DMAC internship\Pupil-labs\work\ceres-windows\x64\Release\libglog_static.lib"   /OUT:build\lib.win-amd64-3.6\pupil_detectors\detector_3d.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\detector_3d.cp36-win_amd64.lib
fatal error C1007: unrecognized flag '-Ot' in 'p2'
LINK : fatal error LNK1257: code generation failed
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1257`

I've followed carefully the instructions , and when i run setup.py i get this error.
Btw in boost i've defined BOOST_ALL_NO_LIB because the linker was searching for wrong msvc version(14.0 instead of 14.1) even though i've modified my user-config.jam

**Comment by behrooza** [comment]
Could you fix this problem?
The problem is: your boost was build under MSVC 14.1 while at the end MSVC 14.0 "C:\Program Files (x86)\Microsoft Visual Studio 14.0\" is compiling c++ files!!!

We have the same issue in our team and don't know how command line choose this older compiler while MSVC 14.1 is there!
This issue is more related to default c++ compiler and visual studio setup!

Any idea?!

**Comment by gjghks** [comment]
I have the same problem.
this command, "python setup.py build", needs boost 14.0.
however, boost is built by 14.1 as the description.
so, I revised the source in user-config.jam as using msvc : 14.0 ;
then I got the same error above.
how to solve!?

**Comment by GeorgiosSopi** [comment]
Hello.. i have the same issue.
I'm trying to install the pupil labs software to a windows laptop by following the manual for windows dependencies.

The problem that i come up against, is when I'm executing the ->   python setup.py build     in the  (Modify pupil_detectors setup.py) field. 

For some reason the program uses as a default version of mscv the 14.0 instead of the 14.1

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104

**Comment by papr** [comment]
We have removed the requirement to install boost in #1552
