### ISSUE TITLE
Screen Calibration Markers Not Appearing on MacOS

### ISSUE THREAD

**Issue by ColinConwell** [pupil-labs/pupil#1214]
Running screen calibration (from Pupil 1.7) on a MacOS (10.13.5, 2016 Model) results in a blank screen when the 'Color LCD' option is selected. Calibrating on an external monitor still seems to be working.

All other settings are set to default. Is there something I'm doing wrong?

**Comment by papr** [comment]
Just to clarify, you are using a MacBook and it does not have a Touch bar, correct? Are you running the bundled application or from source?

**Comment by ColinConwell** [comment]
MacBook Pro Model with Touch Bar. I am running to the Bundled application.

**Comment by papr** [comment]
Please use the window/non-fullscreen option to do the screen calibration until this issue is fixed. I am to 85% sure that the touch bar is the reason that the markers are not displayed correctly. Unfortunately, I do not have immediate access to such a MacBook. I will try to investigate the issue as soon as I do.

**Comment by papr** [comment]
I was able to run Capture on a MacBook with touch bar but it displayed the calibration procedure as expected. Really not sure what the reason might be. :-/

**Comment by papr** [comment]
Maybe also related to https://github.com/pupil-labs/pupil/issues/1381

**Comment by papr** [comment]
@ColinConwell Is this issue still unresolved when using the most recent version of Pupil Capture?

**Comment by papr** [comment]
I will close this issue until there is further feedback.
