### ISSUE TITLE
Change in eye-tracking accuracy due to luminance changes

### ISSUE THREAD

**Issue by callummole** [pupil-labs/pupil#1270]
Hi Pupil, 

This isn't a technical issue, just looking for some practical eye-tracking advice.

I am wondering how changes in pupil size from Calibration to Tracking affect eye-tracking accuracy. Consider the case where calibration is on bright on a bright (white) background, then subsequent eye-tracking is on a background that is significantly darker (so the pupil size has changed). Will the change in pupil size interact with the calibration, and should I expect to see a notable reduction in eye-tracking accuracy that is worth being concerned about? 

Have you guys done any tests on this?

Thank you,

Callum

**Comment by papr** [comment]
We did not check this explicitly but my colleague said that big changes in pupil size might influence gaze estimation. You should not see any notable reduction in accuracy though. Nonetheless, it is recommended to calibrate in the environment that you will do your experiment in.

**Comment by jhdewitt** [comment]
Hello callum,

It is possible to accommodate for difference between calibration environment brightness and experimental environment brightness resulting in reduced accuracy. Angle kappa causes this.

I've encountered this causing accuracy issues in the past with other software; have not tested w/ pupil specifically under the conditions you described.

The problem arises from the pupillary axis and the visual axis ("true" line of sight) being offset in our eyes. Humans have the fovea offset a little bit outwards (temporally), so that the line of sight is slightly biased inwards (nasally). Literature often refers to this angle as kappa or lambda. The angle is usually small, around 5°, and does not change much with age.

Here's some images to help clarify:

[kappa basic](http://2.bp.blogspot.com/-PiDmmiA7Zgo/Tzd4pyvOfdI/AAAAAAAAApE/G5tWOCMa9C0/s640/kappa.jpg)

[x vs y fovea offset](https://lh4.googleusercontent.com/-5MDcjSb8MuE/TX-8NEdszWI/AAAAAAAAAWY/NcwGQP0IiSE/s1600/angulokappa_edad.jpg)

Hope this helps with context. Perhaps a per-user calibration could be possible for situations where experimental luminance covers a wide range and tight accuracy is desired. Maybe a default could be baked into the software, since the angle is relatively similar between people.

Does anyone know if pupillary/visual axis offset is specifically compensated for with pupil?

**Comment by papr** [comment]
This issue is stale. It can be reopened if necessary.
