### ISSUE TITLE
'surface' topic sampling frequency

### ISSUE THREAD

**Issue by PanBartosz** [pupil-labs/pupil#1271]
Hello! 
My problem:
In the nutshell: listening to `surface` topic generates much fewer messages than `gaze`.

When I listen to `gaze` or `pupil` topic using Pupil Remote plugin I receive roughly 120 messages per second which seems correct considering sampling frequency of 120Hz. However when I listen to "surface" topic it generates only about 30-40 messages per second. It doesn't seem to be bounded by framerate of world camera (I changed settings from 30 to 60 fps and did not observe any difference). I guess that mapping gaze to a surface slows down sampling rate. 

Background:
I try to write simple Python library which can be used running experiments in PsychoPy. Its purpose is to record gaze in relation to various area of interests defined in the stimuli. In order to do that I mapped coordinates of the gaze to a screen using surface tracker. Unfortunately this approach doesn't work because of decreased sampling rate connected to sufrace tracker.

UPDATE:
In pupil player's offline exporter gaze positions on surface seem to be sampled at correct rate. It gives me hope that it can work also in pupil capture?

**Comment by mkassner** [comment]
the surface tracker will supply surface data at the the world camera frame rate. If the CPU is maxed out there may be reduced framerate. We group the gaze samples that come at higher freq into these surface events so you should get 120gaze samples per second but the will be grouped into 30 or so surface events per second.

**Comment by papr** [comment]
This issue seems to be resolved.

**Comment by linussun** [comment]
@papr May we please re-open this issue? I would like to have access to gaze.3d._on_surface samples as soon as they are calculated. Can they be published immediately to the IPC backbone? 

The reason: I am using pupil-labs to generate a digital to analog signal which can be nearly instantly visualized and used in psychophysics suites such as psychopy, monkeylogic, psychetoolbox etc... This works very well when subscribing to "pupil.0" topics (the polling is done in <2ms), however very slow for surface. topics because the 'gaze.3d.01._on_surface' gaze samples are grouped and published on low frequency 'surfaces.Surface n' topics as described above. 

Thank you.
