### ISSUE TITLE
Exporting Defined Annotations for Future Use?

### ISSUE THREAD

**Issue by Haaaaaank** [pupil-labs/pupil#1293]
Hi,

I was wondering if previous definitions of annotations (name-hotkey) can be saved and loaded for future use? And, is it possible to assign hotkeys for the next fixation/previous fixation?

Thanks,
Han

**Comment by papr** [comment]
Annotation definitions are stored as part of session settings. These reset every time the software version changes since we do not support forward-compatibility. There is also no method for importing/exporting them.

The hotkeys for jumping fixations are:
- forward: `f`
- backwards: `F`

These are hardcoded and cannot be changed from the ui.
