### ISSUE TITLE
[Tool request] - The ability to view the performance of an Intrinsic Matrix

### ISSUE THREAD

**Issue by RSKothari** [pupil-labs/pupil#1327]
The ability to view the performance of a world camera Intrinsic matrix.
Suggested metric - Vergence angle between left and right gaze normals.

**Comment by papr** [comment]
Apologies for the lack of a response. As the vergence of gaze angles depends on a calibration, this metric would include any errors caused by gaze mapping and therefore be biased.

Nonetheless, we are not planning on adding new features to Pupil Core in the new future based [on our motivation/road map for Pupil Core](https://github.com/pupil-labs/pupil/releases/v2.0). This tool can be implemented as an external script that reads the `*.intrinsics` files from the `~/pupil_capture_settings` folder after a successful intrinsics estimation. See the [_Other Files_ section of our file format documentation](https://docs.pupil-labs.com/developer/core/recording-format/#other-files) on how to read these files.
