### ISSUE TITLE
Missing World Camera feed

### ISSUE THREAD

**Issue by Tzndrm** [pupil-labs/pupil#1369]
Hi There, 
I am having a problem to access to the world camera, in the Backend Menager under Local UVC source only appear with a validate name Pupil Cam2 IDO ( which is the pupil one). I cannot perform any calibration. . Did you ever had this issue?  Thanks 

![error_word camera 2](https://user-images.githubusercontent.com/43857944/47919203-16534880-deaf-11e8-9fbf-6701b45a3039.png)

![error_world camera](https://user-images.githubusercontent.com/43857944/47919299-4ef32200-deaf-11e8-84ad-01bdec0e78a6.png)

**Comment by willpatera** [comment]
@Tzndrm this looks a lot like a driver installation issue. Please can you try the following:
1. Open device manager and select `View > Show hidden devices`
2. Close all Pupil software apps
3. Right click `pupil_capture.exe` and run as administrator. 

Please send a screenshot of the device manager with the above noted settings so that we can remotely debug.

**Comment by willpatera** [comment]
Hi @Tzndrm It has been a few months, since this issue was opened. I'd like to follow up to see if this was resolved. If so, we can close this issue.
