### ISSUE TITLE
pupil diameter goes crazy

### ISSUE THREAD

**Issue by gaiaspicciarelli** [pupil-labs/pupil#1513]
Hi there,

we are doing some recordings with a binocular Pupil labs glasses (without world camera as we don't need it) but we are having troubles with the diameter datas because sometimes it goes up to 15 or 30 mm (and that's impossible), even with a good confidence. 
We were wondering if it's a normal thing (and then we have to remove that kind of datas from our analysis) or if they depend on the parameters we set (pupil min and max, pupil intensity range). 
We usually put pupil min at 20 and max at 100, and adjust the pupil intensity range by viewing the blue area with algorithm function.
Can you help us?
Thanks a lot

**Comment by gaiaspicciarelli** [comment]
Also, can you suggest which number should appear in the center of the 3 circles (big red, green and little red ones)? We always put the green one into the boundaries at it's said but we don't understand if it should be right in the middle or nearer to the little red one. We see the number in the center but we don't know which should it be. 
Also, if we record both eyes, should the parameters and the diameters be the same for both eyes?

**Comment by papr** [comment]
Pupil min, max and intensity range are parameters for the 2d detection algorithm.

The intensity range defines the required darkness of the pixels that are to be considered a pupil. Pupil min and max are thresholds to discard pupil candidates that exceed these given boundaries (in pixels). There is not need for the green circle (current pupil size) to be perfectly in the center between min and max (red circles), but it should be on average. As the 2d pupil size is measured in pixels, the pupil size also depends on how close the camera is to the eye. Therefore, the parameters can differ for both eyes.

In 3d pupil detection, the eye process tries to fit new 3d eye models when newly detected 2d pupil data does not fit the previous 3d model, e.g. due to device slippage. Sometimes, it can happen that the 3 model does not fit well to the reality, e.g. its position is estimated to be further away from the camera than it actually is, and produces smaller/higher pupil diameters than expected. 

@gaiaspicciarelli Could you you check if the pupil diameter jumps correlate to changes in sphere center locations (`sphere_center_x/y/z` in `pupil_positions.csv`), in your case?

Also, be aware that the current 3d pipeline does not take corneal refraction into account. More information on the effects of corneal refraction can be found here: https://perceptual.mpi-inf.mpg.de/files/2018/04/dierkes18_etra.pdf

I hope I was able to answer your questions and will close the issue. Let me know if you have questions related to this topic and we can reopen the discussion. Feel free to create new issues, if you have questions that are related to a different topic.

**Comment by gaiaspicciarelli** [comment]
Hi Pablo, thanks for the answer, I understood much more about how 3D model works! 
I checked the data you asked and, as you supposed, when the crazy numbers happen, there are changes in sphere center locations. I attach you a screenshot of a part of the pupil_position file (attach n.1). 
So, I must assume that these data aren't reliable and so we cannot use them. 
But, during other trials, there is always this kind of change in sphere center location but not like this but like a series of data with a certain sphere center values and then they changes and there is a series of other values. I don't know how to explain it better, so I attach another screenshot of another pupil_position file (attach n.2). 
So, my question is: it is normal that these values are going to change during a recording but in the second way or they must not change during all the entire recording? 
Thanks a lot! 
![attach n 1](https://user-images.githubusercontent.com/50203021/58476267-934a5600-8150-11e9-847e-32985b6b4325.png)
![attach n 2](https://user-images.githubusercontent.com/50203021/58476270-947b8300-8150-11e9-9ee4-496411a8b79b.png)

**Comment by papr** [comment]
Apologies for the delayed response.

Wrong diameter estimations - It can happen that the fitted eye model does not correspond to the actual eye position and is positioned further away than expected from the camera. This results in pupil diameters being over-estimated. Unfortunately, there is no good solution at the moment that could be applied in real time. My suggestion in your case would be to manually remove all data points that have the same model_id as the data points that generate over-estimated pupil diameters. Additionally, you can try to decrease the model sensitivity in the 3d detector menu during pupil detection. This results in fewer refits of the model.

**Comment by gaiaspicciarelli** [comment]
Hi, thank you for the reply. 
Okay, so we will try with that. Can you suggest which model sensitivity we should use in order to have fewer refits of the model? Or we have to try decreasing it and look at the data to find the one that it's better for our case?
