### ISSUE TITLE
World camera swaps to another world camera during the session

### ISSUE THREAD

**Issue by prernaaneja** [pupil-labs/pupil#1521]
[capture.log](https://github.com/pupil-labs/pupil/files/3276980/capture.log)
Hi,

We have two pupil captures running during the task. However, most of the time the world camera swaps to another person's world camera and we end up having two pupil capture windows with the same participant's world view.

I have attached the capture.log for this.

Best,
Prerna

**Comment by papr** [comment]
Hi, this is the current fallback behavior when the current device disconnects. We won't be able to change it until the next release but we are planning on changing it. Until then, you can use v1.12 which allows you to automatically select cameras for each window given a selected device.

**Comment by papr** [comment]
Unfortunately, the cameras do not have a unique identifier which would allow us to differentiate between multiple connected headsets. Therefore, the camera selection is non-deterministic. Since this is not a software issue, I will close this. We will consider this issue for future hardware revisions.
