### ISSUE TITLE
World camera dropping frames 

### ISSUE THREAD

**Issue by pefortin** [pupil-labs/pupil#1570]
Problem: The recorded world camera camera video is often shorter than the eye camera video, which is a consequence of missing frames. These frames appear as long grey periods when playing the files in Pupil player.

example file duration (m:s): 
eye - 35:28, world - 18:53
eye - 30:36, world - 27:07

I have not had issues in the past 1-2 months, but started doing longer recordings (~40 minutes) and it started appearing. I am also tracking 7 surfaces in total, but there is rarely more than 3. 

Configuration:
Pupil capture: 1.12.17
OS: Ubuntu 18.04, up to date
i5-7200U CPU @ 2.50GHz × 4 , 15.6 GiB ram, Intel HD Graphics 620
Pupil core with fast world camera, and 200Hz monocular camera
World camera: 1280x720 at 60fps
Eye camera 400x400 at 120 fps

Also tested with:
AMD Ryzen 7 1700X 8 core, 3.6 GHz, 32 GiB ram, ssd, running windows 10 with ~25% frame drop
I5-4690k 4 cores, 3.5 Ghz, 32 GiB ram, hdd, running ubuntu 18.04 with ~13% frame drop

This is the only thing holding back my study so if anyone has a solution, I would be extremely thankful.

**Comment by pefortin** [comment]
I moved to a fourth computer that is overclocked, with very good single core performance and it seems to have fixed the issue. However, to avoid fps drops, I need to turn off the online surface recognition.

I would advise to include hardware system requirements on the website. It took me a while to find a computer that worked.

 AMD Ryzen 7 1700X 8 core, 3.6 GHz, overclocked to 4.1 GHz, 32 GiB ram, ssd, running windows 10 with ~25% frame drop

**Comment by papr** [comment]
@pefortin Apologies for the delayed response.

Yes, you are correct, that dropped frames are a result of the system not being able to keep up. It might also be helpful to turn off other features, e.g. accuracy visualizer (#1611).

Generally, it is difficult to define a set of system requirements since the required performance heavily depends on the setup (active plugins, camera resolution and frame rate, pupil detection type, operating system).
