### ISSUE TITLE
Surface tracker crashes on windows

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil#1588]
The surface tracker seems to consistently crash on windows (but not on Linux) when
a) using a lot of surfaces (>10) at the same time and
b) when performing an action like moving the corner of a surface before the results of a previous action have finished computing.

This was feedback from ETRA. Not yet reproduced.

**Comment by papr** [comment]
We were not able to reproduce the crash itself, but noticed that Surface Tracker does not perform well on Windows when one has defined a lot of surfaces. This is due to each surface starting its own background processes for different tasks. This generates a lot of overhead on systems that use `spawn`, i.e. Windows.

**Comment by papr** [comment]
@mkassner has proposed to use `threading` instead of `multiprocessing`. @romanroibu will look into the implementation of this proposal.
