### ISSUE TITLE
'gaze_on_surface' publish frequency and realtime accuracy question

### ISSUE THREAD

**Issue by linussun** [pupil-labs/pupil#1601]
Can we have access to gaze.3d._on_surface samples as soon as they are calculated: i.e. may they be published immediately to the IPC backbone? Currently they are grouped with world camera rates under the topic 'surfaces.Surface n' 

With regards to the accuracy of the gaze location on surfaces: is an assumption made that the surface has not moved until the new world frame in order to calculate gaze_on_surface locations? 

If this is the case: Can gaze on surface from the previous frame be interpolated/updated to account for surface movement in the next frame? This should be easy to do offline.  In the online case, would it be possible to implement a baysean filter to predict the location of the surface in upcoming frame? 
 
Thank you.

**Comment by linussun** [comment]
Can we have access to gaze.3d._on_surface samples as soon as they are calculated: i.e. may they be published immediately to the IPC backbone? Currently they are grouped with world camera rates under the topic 'surfaces.Surface n' 

With regards to the accuracy of the gaze location on surfaces: is an assumption made that the surface has not moved until the new world frame in order to calculate gaze_on_surface locations? 

If this is the case: Can gaze on surface from the previous frame be interpolated/updated to account for surface movement in the next frame? This will be easy to do offline.  In the online case, would it be possible to implement a baysean filter to predict the location of the surface in upcoming frame? 
 
Thank you.

**Comment by papr** [comment]
@linussun apologies for the delayed response.

Yes, you are right that gaze is mapped to surfaces in batches each time a new world frame has been captured. This delay cannot be reduced much since gaze is generally mapped in batches in Capture, i.e. in the beginning of each world event loop iteration all recent pupil data is mapped to gaze and published. This event loop frequency depends on the selected world camera frame rate, i.e. the higher the world frame rate the higher the `gaze_on_surface` publish frequency. This also means, that your proposal for an online surface location predictor is not easy to integrate into the existing architecture.

The offline interpolation is possible but we do not plan on implementing it in the near future. But I would be willing to review a corresponding PR if you submitted one. 👍
