### ISSUE TITLE
windows 10 driver set up crash - driver signature enforcement issue

### ISSUE THREAD

**Issue by rrlazar** [pupil-labs/pupil#1650]
On my Windows 10 run Acer laptop pupilcam driver set up was crashing without any error message even when running as admin. Repeating the steps of https://docs.pupil-labs.com/#troubleshooting didnt help either. When I tried installing the libusbk drivers manually via the [UsbK Development Kit Setup](https://sourceforge.net/projects/libusb/), error message showed that driver signature enforcement in windows 10 seemed to be the general issue.

![error message](https://user-images.githubusercontent.com/47449790/65249189-cfd10180-daf3-11e9-869f-9059e031ef29.PNG)

So it turns out I needed to disable the driver signature enforcement, at least temporarily.
For an easy walktrough on how to do that, [follow these instructions](https://windowsreport.com/driver-signature-enforcement-windows-10/).

Once driver signature enforcement is disabled, you should be able to run the set-up of the libusbk driver for instance with the above mentionned [UsbK Development Kit Setup](https://sourceforge.net/projects/libusb-win32/). When installing, choose the v3.0.7.0 version and have the Pupil cam(s) connected via USB while running the set-up. Once installation is finished, you should be able to run the pupil apps and have access to the pupil cam(s) as well.

 ![install](https://user-images.githubusercontent.com/47449790/65250152-69e57980-daf5-11e9-9587-756e94498dc2.PNG)

**Comment by papr** [comment]
Thank you very much! This is valuable information! We have not come across this issue before when following the [`pyuvc` instructions](https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md), though. Is it possible, that you downloaded unsigned drivers, and the drivers linked in the pyuvc instructions are actually signed?

Nonetheless, I will go ahead and close the issue since it looks like you were able to solve the issue by yourself! :)
