### ISSUE TITLE
Pupil Capture mobile

### ISSUE THREAD

**Issue by VicWalDK** [pupil-labs/pupil#1663]
Hey, anyone who have experience with the the pupil capture mobile technology? I am working with pupil capture and are wondering if it is a good idea to invest in a nexus phone and USB-C for using the pupil capture mobile. My project includes movement, therefor the mobile function would be amazing. What are your thoughts and experience with the mobile application? does it work? 
Bets regards

**Comment by papr** [comment]
Hi @VicWalDK Pupil Mobile is an Android App that previews, streams and records the video from the Pupil Core headset. It does not perform any pupil detection/gaze estimation by itself. Instead you need to copy Pupil Mobile recordings to your computer and analyze them with Pupil Player. Check our Youtube tutorials on how to use Offline Pupil Detection and Offline Calibration. https://youtu.be/_Jnxi1OMMTc

The Pupil Mobile workflow uses the same technology as the Pupil Capture workflow, with the difference that you need to use it after the effect.

I will close the issue since it is not a software related technical problem. If you have further questions feel free to join our [Discord community](https://pupil-labs.com/chat) or contact our sales team at info@pupil-labs.com :)
