### ISSUE TITLE
Convert surface coordinates to world coordinates

### ISSUE THREAD

**Issue by JohnTyCa** [pupil-labs/pupil#1687]
I am working on a project and have an idea that would require me to determine a location on the surface in surface coordinates. However, I would then be required to convert the surface coordinates to the world coordinates so I could determine the location of this point on the original video frame. 

Is it possible to convert a surface coordinate to a world coordinate using the homography matrix for a designated video frame? I notice in #753 that the transformation of a world coordinate to a surface coordinate is described, but I am at a loss for computing the reverse. Any help you could provide would be much appreciated, thank you.

**Comment by papr** [comment]
@JohnTyCa Hey 👋 

The `surf_positions<name>.csv` file in the surface tracker export folder includes matrices to transform coordinates from world to surface ("img_to_surf_trans"), and vice versa ("surf_to_img_trans"). Just use the `surf_to_img_trans` matrices in your case.

I hope this helped. I will close the issue since the main question should be answered. If there is anything unclear, let me know and I can reopen the issue.

Please also see https://github.com/pupil-labs/pupil/issues/1616
