### ISSUE TITLE
Blink raw data exporting in real-time

### ISSUE THREAD

**Issue by hayashik** [pupil-labs/pupil#1729]
Hi,
I'm trying to export blink data (at least, start-end blink time stump) to my research.
I find the blink_detection.py, but there is function offline exporter only.
Could you please give some idea on how to export blink raw data in real-time?
Thank you!

**Comment by papr** [comment]
@hayashik Hey, you can subscribe to the real-time blink data using our network api. As a start, you can modify this script to subscribe to `blink` instead of `pupil`: https://github.com/pupil-labs/pupil-helpers/blob/master/python/filter_messages.py#L23

Please be aware, that real-time blinks are not aggregated, i.e. you will receive multiple start and stop events for the same fixation. You can group them by their `id` field.

The Online Fixation Detector starts in line 663 of the `fixation_detector.py` file.

**Comment by hayashik** [comment]
@papr Thanks! 
I could get the blink raw data from your script!
