### ISSUE TITLE
Installation on NVIDIA Jetson AGX Xavier

### ISSUE THREAD

**Issue by Z0org** [pupil-labs/pupil#1736]
Hey everyone,
For a project I need to run the software on a NVIDIA Jetson AGX Xavier. Does anyone have any experience with installing the dependencies and the pupil software?

Thanks :)

**Comment by papr** [comment]
Since it is an ARM based CPU you won't be able to run the bundle. Follow the instructions for the operating system that is installed on the AGX: https://github.com/pupil-labs/pupil/tree/master/docs

Please be aware that probably there won't be pre-compiled versions of all the Python modules. Their compilation might require further dependencies.
