### ISSUE TITLE
Post-processed eye videos cannot be offline detected

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pupil#1797]
Hi,
my workflow was: Record eye videos with pupil capture without pupil detection, compress the video with "handbrake" (www.handbrake.fr) to h264 to save space and at last open the measurement in pupil player and offline detect the pupil (actually did it in pupil service, but doesn't matter). Prior to pupil data format 2.0 it just worked. I updated recently to 1.21 and now I only able to offline detect the untouched eye videos. As soon as I convert them to h264 (or even plain mp4) with variable framerate the log is spammed with 
`[WARNING] video_capture.file_backend: Advancing frame iterator went past the target frame!`
which should "never happen" as it is documented in the source code :) 
The progress bar gets not to the end and the data (pupil positions) is corrupted.

How can I get the compressed videos to work again?

Thanks a lot, you can download two examples of the same recording at:

https://www.dropbox.com/s/gahqsxedlq8azuh/Archiv.zip?dl=0

**Comment by papr** [comment]
We have experienced this issue, too. The problem is that the transcoding drops and duplicates frames as it sees fit. This also results in slightly different frame pts. These do not match our internal timestamp lookup table anymore, and shows the warning respectively.

I remember that there was a way to tell ffmpeg to no drop/duplicate frames, but I do not know the exact parameters anymore and I do not know if it is possible to specify them in HandBrake.

**Comment by mattem86** [comment]
Ok, thanks for the reply. I will try ffmpeg!

But what about the videos I already compressed? Is possible to "fall back" to the frame-by-frame detection regardless of the timestamps?

**Comment by papr** [comment]
Player maps the externally recorded timestamps to the video file's internal timestamps (pts). Specifically, a video yields a series of packets (fast, e.g. raw h264 buffer) which can be decoded to video frames (slow, e.g. `width x height` RGB buffer).

This mapping is used during playback and seeking.

Current assumption by Player:  Every video packet yields a video frame and their pts is equivalent. Therefore, Player maps timestamps to the packet pts (fast) instead of the frame pts (slow).

This assumption breaks after transcoding. Packets can yield none, one, or more frames. Also, their pts are not required to match.

You can change the line below and run from source to use the slow, but correct `timestamp -> pts` mapping. Delete all `*_lookup.npy` files prior to opening the recording in the modified Player version to force the regeneration of the mapping based on frame pts.

```diff
diff --git a/pupil_src/shared_modules/video_capture/utils.py b/pupil_src/shared_modules/video_capture/utils.py
index b29026d7..01bc97a8 100644
--- a/pupil_src/shared_modules/video_capture/utils.py
+++ b/pupil_src/shared_modules/video_capture/utils.py
@@ -212,7 +212,7 @@ class Video:
         self.ts = self._fix_negative_time_jumps(self.ts)
 
     def load_pts(self):
-        packets = self.cont.demux(video=0)
+        packets = self.cont.decode(video=0)
         # last pts is invalid
         self._pts = np.array([packet.pts for packet in packets][:-1])
```
