### ISSUE TITLE
Surface tracking without markers/april tags

### ISSUE THREAD

**Issue by defaultuzer** [pupil-labs/pupil#1804]
Dear everyone, 

after collecting a lot of data in a simple picture-viewing paradigm with our main measurement being pupil diameter, we were wondering if there is a post-hoc chance to still do surface tracking analysis with pupil player. 
i.e. we did not incorporate any markers/april tags in our experiment and ideally would like to measure a simple on/off analysis with the picture as the area of interest ('on') and the surroundings on the screen as the 'off' value. 

Is it at all possible to manually define surfaces in pupil player without april tags visible in the video? 

Our lab is new to using the pupil labs hardware and software, so any input would be much appreciated. 

Thanks and best regards!

**Comment by pfaion** [comment]
Hi @defaultuzer 

currently Pupil Player only supports marker-based surface tracking. We plan to add marker-less area-of-interest tracking at some point in the future, but I cannot give you an ETA for this.

So you will have to write your own code to do this analysis. Since your image will certainly be of rectangular shape, I'd recommend thinking about doing this analysis in unprojected image space, e.g. getting rid of the camera distortion. For this you will have to use the camera distortion matrix. You can find it in the file `world.intrinsics` in your recording. It is basically a dictionary serialized to a file with msgpack. You can use the function `file_methods.load_object()` to load it into a Python dictionary:
https://github.com/pupil-labs/pupil/blob/f3a48dfa38d706c09c1cdb571b4d578e8d1b5528/pupil_src/shared_modules/file_methods.py#L72-L92
The resulting dictionary can have multiple distortion matrices for different resolutions. You should look at the keys of the dictionary for more information. See e.g. the following snippet for how we use `load_object()` to load intrinsics specifically:
https://github.com/pupil-labs/pupil/blob/f3a48dfa38d706c09c1cdb571b4d578e8d1b5528/pupil_src/shared_modules/camera_models.py#L155-L205
