### ISSUE TITLE
defining surfaces by selecting marker ID from a table

### ISSUE THREAD

**Issue by ben24o** [pupil-labs/pupil#186]
Is it possible to define surfaces by typing or selecting marker IDs from a list or table?

Is Pupil Player capable of listing all marker IDs in one video file?

**Comment by mkassner** [comment]
All of this would be easy to implement. Can you elaborate on what you want to achieve with this?

**Comment by cpicanco** [comment]
I think this request is related to #87

**Comment by ben24o** [comment]
1- When I add a surface, sometimes, one of the corners is out of the scene that make it very challenging to modify the surface. 

2- I was thinking that by using a list of detected markers, it would be possible to define surfaces bigger than the camera view.

**Comment by cpicanco** [comment]
Hi @ben24o , is the surface always partially out of the scene? If the surface shows up in some frames, you can seek to this frame and define the surface there. Pupil will deduce the other corners if at least one (better two, though) corner at the scene.

**Comment by ben24o** [comment]
Hi @cpicanco, 
I know that I can modify surfaces at any frame that they look better at. What I have confronted is that when I click "add surface" sometimes one of the corners is defined out of the scene. When I move back and foth in the video file, If that corner appears in the view then I can drag it to the position that I want; the real challenge, however, is when the corner does not show up in the view. Thus, defining surfaces by using a table of detected markers would give us more control.

**Comment by cpicanco** [comment]
Please, when I say:
- "define a surface", it means "click add surface button".
- "real world surface", it means what you expect to be a defined surface. Of course, when you click the `add surface` button, the resulting surface may not correspond to the real world surface. And that sucks, because editing surfaces by drag and drop is challing with a lot of them. So, right now I am thinking about a scenario where there is need to edit anything...

Now, let me see if I really understand what you want:

1) You are using some markers in the real world, lets say 6 markers. What you want is the front glass of a car as the "real world surface". So, you stick the markers at the corners of the glass and at the up and down midpoints.
2) All you need to do is to seek to a single frame where all the markers can be seen all together and then "define a surface". Of course, you can't do that, because the real world surface is too big.
3) In order to do that, you need Pupil to scan all the video, detecting all the markers, and then returning to you a list, so you could choose what markers you want to "define a surface".

**Comment by ben24o** [comment]
you got that right

**Comment by mkassner** [comment]
The problem with that is that we don't know the relation of all markers of one surface in  a single shot. We need this to construct the surface. Just knowing markers without relation to each other is not enough for surface registration. 

I do see a need for this request. I m just not sure on how to implement it.

**Comment by cpicanco** [comment]
I had an idea. [WiTrack](http://news.mit.edu/2013/new-system-allows-for-high-accuracy-through-wall-3-d-motion-tracking-1211) is a camera-less 3d tracking system. I think the same principle (radio emitters-receivers) could be applied to make camera-less markers and track the field of view in relation to the camera. As you might be thinking, it would require new hardware and software. Maybe in the future Pupil could be committed with a diversification of their business, providing wider set of hardware and software to track things.

**Comment by willpatera** [comment]
@mkassner - I think this can be closed now that the surface detector has been improved.

**Comment by mkassner** [comment]
Agreed!
