### ISSUE TITLE
Eye camera and world camera of Pupil cannot be read simultaneously by C++ OpenCV in Windows 10

### ISSUE THREAD

**Issue by 962557346** [pupil-labs/pupil#1904]
Hey, recently I need to open eye camera and world camera of Pupil simultaneously  by C++ OpenCV in Windows 10.  
Firstly, I used the means of [219](https://github.com/pupil-labs/pupil-docs/issues/219) to read image, which uninstalls the " libusbK USB Devices"  in the Device Manager and then "Scan for HW changes". Finally "Integrated Camera" and "Pupil Cam 1 ID2" are listed  in the "Cameras" category.
Secondly, I used the below C++ OpenCV code to capture images:
```C++
int main()
{
	VideoCapture eye = VideoCapture(1); // Integrated Camera
	VideoCapture world = VideoCapture(2);  // Pupil Cam1 ID2
	cv::Mat img_eye;
	cv::Mat img_world;
	std::cout << (eye.isOpened()) << std::endl;  // 1
	std::cout << (world.isOpened()) << std::endl; // 1
	if ((!eye.isOpened()) || (!world.isOpened()))
	{
		printf_s("Cannot open!");
		return 0;
	}
	while (true)
	{
		eye >> img_eye;
		world >> img_world;
		if (img_eye.empty())
		{
			std::cout << "eye empty" << std::endl;
		}
		if (img_world.empty())
		{
			std::cout << "world empty" << std::endl; //  world empty is printed.
		}
		if ((img_eye.empty()) || (img_world.empty()))
		{
			break;
		}
		cv::imshow("img_eye", img_eye);
		cv::imshow("img_world", img_world);
		cv::waitKey(30);
	}
	return 0;
}
```
It didn't show any image and printed the "world empty" that showed the img_world is empty. But when I read eye image or world image individually, it can imshow eye image or world image.  It seems that when reading eye image and world image simultaneously, the previous videocapture may block the late videocapture in Pupil. 
I also noticed in [1422](https://github.com/pupil-labs/pupil/issues/1422) you used the [pyuvc](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py) to capture images.  But the code is performed in python. Is there a solution that  can open eye camera and world camera simultaneously  by C++ OpenCV in Windows 10? 
Looking forward to your reply.

**Comment by pfaion** [comment]
Hi @962557346 

just for clarity: are you running Pupil in the background? Since this will probably not work.

Otherwise, you are not using Pupil at all here, but just accessing USB cameras with OpenCV. I can only refer you to the documentation of OpenCV here: https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html

Have you tried using `VideoCapture::read(...)` instead of the streaming operators?
Also please note that `VideoCapture(1)` might be the built-in camera of your computer, e.g. webcam and not the eye camera. The name `Integrated Camera` seems to suggest so.

If you are interested in trying libuvc: [here's the link to the C API](https://ken.tossell.net/libuvc/doc/), which you can also use from C++.
Please note that **pyuvc** is a Python wrapper around a [custom modified version of libuvc](https://github.com/pupil-labs/libuvc). 
Also note that when using libuvc on Windows, you will have to install our custom libusbk drivers again.
