### ISSUE TITLE
error timestamp, which is negative?

### ISSUE THREAD

**Issue by BLUEHL** [pupil-labs/pupil#1925]
Hello, I recorded a video from the capture software for a period of time, and found that the timestamp under info.csv and world_timestamp in the recording folder are all negative values, which is obviously wrong. I would like to ask what is the reason, I should How to get the correct timestamp information. My operating system is Windows and the capture software version is v1.19.
![image](https://user-images.githubusercontent.com/47234086/85519352-f1878800-b633-11ea-8965-0fab4b3352f0.png)

**Comment by papr** [comment]
@BLUEHL Hi, technically, timestamps can be negative as long as they are monotonically increasing. This seems to be the case here. By default, the timestamps should not be negative. Have you been synchronizing time via Pupil Remote or Time Sync?

**Comment by papr** [comment]
@BLUEHL If you like you can share the recording with data@pupil-labs.com and we will have a look. :)

**Comment by BLUEHL** [comment]
Thank you for your prompt reply. Although the timestamp is negative, I can still continue my work. I restored both the capture and player software to the default operation. The timestamp is still negative. Yes, I am also happy to share the recording file

**Comment by papr** [comment]
@BLUEHL Do you mean that new recordings created, after restoring to defaults, also contain negative timestamps. In this case, it looks like the monotonic clock is returning negative timestamp values. Technically, this is not problematic as long as the values are monotonically increasing, which they are. Your recording looks fine otherwise. I will, therefore, close this issue.
