### ISSUE TITLE
Problem accessing network data for "gaze_on_surfaces"

### ISSUE THREAD

**Issue by lwoffice** [pupil-labs/pupil#1926]
Hello,

I am trying parse the surface messages (in C++) https://docs.pupil-labs.com/developer/core/overview/#surface-datum-format
and I have already figured out to parse "m_to_screen" and I transformed the 4 surface corners already.
Right now i am struggling to access the content of the "gaze_on_surfaces". 

From what I understand from the documentation, it should be an array of MapStrMsgPackObj objects. I assume that in my case the array size should be one, because I have defined one test surface only, but not sure about that, too.

I tried this:
auto gaze_on_surfaces = mmap["gaze_on_surfaces"].as<std::array<MapStrMsgPackObj, 1>>();

This line of code already fails at runtime, so it is not the correct use of 
mmap["gaze_on_surfaces"].as

Can anyone please help me out how I can access this "gaze_on_surfaces" content ?

Thank you

**Comment by lwoffice** [comment]
For better understanding what I have already, below my code for handling payload messages. All the stuff at the beginning works fine

void cSPUPupilEyeTracker::process_pay_messages() {
  msgpack::unpacker pac;
  pac.reserve_buffer(payload_bytes_received);
  memcpy(pac.buffer(), (char*)zmq_msg_data(payload_message), payload_bytes_received);
  pac.buffer_consumed(payload_bytes_received);

  // deserialize it.
  msgpack::unpacked msg;
  pac.next(msg);
  msgpack::object obj = msg.get();
  MapStrMsgPackObj mmap = obj.as<MapStrMsgPackObj>();
  
  auto transform_matrix =  mmap["m_to_screen"].as<std::array<std::array<double, 3>, 3>>();
  //process matrix and calculate corner points of the surface in screen pixel coordinates
  ...

  //fetch gaze point within the surface
  auto gaze_on_surfaces = mmap["gaze_on_surfaces"].as<std::array<MapStrMsgPackObj, 1>>();
  //Fails at runtime here

**Comment by pfaion** [comment]
Hi @lwoffice 

these messages are sent for every world frame. Since the world cameras run usually on a lower frame rate than the eye cameras, a world frame usually contains multiple gaze datums. However, the number of gaze datums can be variable based on network jitter.

Unfortunately we haven't worked with the C++ msgpack library and cannot really offer any support here. I assume the dynamic length might cause you some headache here, but there must be a way to solve this. In the end Python is able to deserialize the data without problems. Can you deserialize in a dynamic-size datatype such as `std::vector`?

Although it's very different, I'd suggest having a look at [our Python example](https://github.com/pupil-labs/pupil-helpers/blob/master/python/filter_gaze_on_surface.py).

**Comment by pfaion** [comment]
@lwoffice I also notice you are working with an older version of Pupil? Since the `m_to_screen` does not exist anymore in the latest versions. I assume you have noticed that already, since the documentation you linked to does not include this key anymore. I just wanted to make sure that you are aware that your data might look different than in our current documentation. Maybe you can actually use Python to figure out the exact format of your data in case your haven't done this already.

**Comment by lwoffice** [comment]
Hi, well the version stuff: yes, you are right, I had an older version because I used the old marker sets. I used https://kawanet.github.io/msgpack-lite/ to get the message content, but I somehow confused it now with the newer documentation stuff. Sorry, I guess I will get it done now :)

Python: I work in a driving simulator environment and I have to use C++.

**Comment by pfaion** [comment]
Ok, good luck with this then :)
I'll close the issue for now as I think I answered your questions.
