### ISSUE TITLE
Questions about world_index  

### ISSUE THREAD

**Issue by hz-pupil** [pupil-labs/pupil#1957]
Questions about world_index  
The world video is framed into pictures with the same frame rate by ffmpeg. 
The command is “ffmpeg -i E:\data\2020_05_21\003\exports\001\world.mp4 -r 96.561255 -ss 0 -f image2 E:\data\2020_05_21\003-10\out-%06d.png”
The rate we set is 96.561255 with is calculated from the file named “export_info.csv”. Accoding to the message from the file named “export_info.csv”, the frame index range is 0 – 5962. 
And the total number of pictures we obtained are 5965.
It is not much difference.
And then we compared the index of 3 pictures we are interested.
For example, the world_index are 2975, 4189 and 5522 captured from pupil player, respectivliy. 
The coresponding index are 3063, 4246, 5538 captured from the pictures framed by ffmpeg, respectivliy.
The difference are 88, 57 and 16, respectivliy.
They are quite different and there is no regularity.

How do pupil player exported the world_index? What’s wrong with my framing process?
Ask for help from experts!
Thanks!

**Comment by pfaion** [comment]
Hi @hz-pupil, what's the goal you are ultimately trying to achieve with the resampled framerate?

As the frame rate of the world video can naturally vary, the differences when resampling to a fixed frame rate will also be arbitrary. So at least from a high-level point of view, I think the behavior you are observing is reasonable. I'm not sure how FFmpeg's resampling algorithm works in detail, so I cannot comment on any specific details here.

**Comment by pfaion** [comment]
@hz-pupil thinking about this again: are you just trying to extract every frame from the exported video?

In this case, you cannot assume a fixed frame rate, as Pupil exports the frames in the same framerate as recorded. As I mentioned above, the recording framerate can naturally fluctuate due to transmission latencies.

Maybe just running the command without a fixed frame rate would already produce the desired results? Can you test the FFmpeg command without the `-r 96.561255`?

**Comment by hz-pupil** [comment]
@pfaion  Yes, I want to extract every frame from the exported video.  
For example, the total time of the world video recorded is 3 second and there are 6000 frames. At the first second, it’s a red color; at the 2nd second, it’s a green color, the corresponding start frame NO. is 2000 ; at the last second, it’s a blue color, the corresponding start frame NO. is 4000 ;. And then I want to extract the frame NO. 2000 and 4000. I can read the data from the exported pupil_positions.csv file according to the frame NO. 2000 and 4000.
The the frame NO. 2000 and 4000 can be extracted manually one by on from the pupil player. However, when there are many videos, this is very cumbersome. We want to automatically extract them.

**Comment by hz-pupil** [comment]
@pfaion I  have test the FFmpeg command without the -r 96.561255,  It's failed . More than 30000 frames are obtained. Actually only 5963 frames.

**Comment by pfaion** [comment]
@hz-pupil ok I looked at the FFmpeg documentation at it seems the parameter you need to extract frames from a variable-framerate movie is `-vsync 0`. So the following should be everything you need:
```
fmpeg -i E:\data\2020_05_21\003\exports\001\world.mp4 -vsync 0 E:\data\2020_05_21\003-10\out-%06d.png
```

The `-ss 0` is not needed since FFmpeg will just extract all original frames with the `-vsync 0` option. This only makes sense if you don't want to start at `0`.

The `-f image2` is also not needed since FFmpeg will infer the output format from your `.png` template.

This command works for me locally when extracting the frames of an exported world video. I get the same number of frames as displayed in Pupil Player or as there are entries in `world_timestamps.csv`. Please give it a try.

**Comment by papr** [comment]
I can confirm this works as expected. We will add this command to our developer documentation for future reference.

**Comment by hz-pupil** [comment]
@papr Thank you for your kind reply. We have tried the command you provided. It's Ok. And finally, we find that the soft, which we used to capture the frame we are interested, only read the avi  format of the video with MJPEG. We changed the mp4 to avi with MJPEG, and then the soft  captures the frame correctly.
