### ISSUE TITLE
Pupil Player 0.5.7-1 crashes at start-up on Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by dschreij** [pupil-labs/pupil#196]
When I try to start pupil_player on Ubuntu 14.04 64-bit I get the following error:
```
daniel@Eyetracker:~$ pupil_player
Traceback (most recent call last):
  File "<string>", line 91, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/video_capture", line 23, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0: undefined symbol: orc_program_new_from_static_bytecode
```
Is it a problem with my system configuration, or in Pupil Player? The versions prior to this one worked fine!

**Comment by mkassner** [comment]
For the last release, we did update libav and compiled opencv with the new libs to fix some jpeg trouble and this must be the cause here. 

I cannot replicate this on any of my test machines (for Ubuntu that is 1 for 12.04 and 4 for 14.04 x64). I also just did a software update and it still works. That makes it hard to debug and I m not sure if the fault is with the bundle or your setup. 

Maybe a software update helps?

**Comment by mkassner** [comment]
@dschreij  Please reopen if this is still an issue.

**Comment by dschreij** [comment]
I did a software update in 14.04 from the repositories, but didn't get around to updating opencv from souce. I hope to do that soon and report back here afterwards

**Comment by dschreij** [comment]
I updated OpenCV to 3.0.0 and the error still occurs. On another machine I have running on Ubuntu 14.04 everything works fine though, so it is probably system related.

**Comment by mkassner** [comment]
This has now been fixed. The latest release will run on your problem machine as well.
