### ISSUE TITLE
No more audio capture - how to cope with that?

### ISSUE THREAD

**Issue by gaiaspicciarelli** [pupil-labs/pupil#2010]
Hi,

with deep disappointment I found out that you decided to remove the Audio capture plugin. It was a crucial plugin for my research work, because I need to compare audio target with pupillometry. 
It's too difficult to let the audio recording start on the computer with another software and then start the pupil recording with pupil labs, the risk is to lose lots of useful data. 
Can you suggest a way to cope with that?

**Comment by papr** [comment]
Hi @gaiaspicciarelli 

It was a very difficult decision for us to discontinue this feature but as it turned out it was too difficult to get it right for a wide variety of microphones on all three of our supported operating systems.

Do you have control over the source of the audio target? Instead of recording the audio and analyzing it post-hoc, I suggest sending timestamped annotations to Capture indicating the timing of the audio target. You can base your work on our [remote annotation example](https://github.com/pupil-labs/pupil-helpers/blob/master/python/remote_annotations.py).

**Comment by gaiaspicciarelli** [comment]
Ok, thanks for your answer. 
Yes, I have the same audio target for each participant: are you saying that it's possible to automatically assign annotations to a certain timestamps? Because I used to do it manually during my post-hoc analysis (so listening again to the audio recording and put the annotations when the participant gives the answer).

**Comment by papr** [comment]
Exactly. For this to work, you need a script that is able to accurately timestamp the audio playback. This is easiest when the script is also responsible for playing back the audio, e.g. via https://psychopy.org/api/sound.html
