### ISSUE TITLE
deploy_capture doesn't build working app on mac

### ISSUE THREAD

**Issue by steven807** [pupil-labs/pupil#205]
As of version 0.6.20, I can run capture (via "python main.py") successfully.  And when I run "./bundle.sh" from within deploy_capture, it successfully builds a DMG.  But the resulting app exits immediately.  Running the generated binary from the command line produces:

    % ./pupil_capture
    Traceback (most recent call last):
      File "<string>", line 82, in <module>
      File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
        exec(bytecode, module.__dict__)
      File "/Users/grady/work/pupil-labs/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/eye", line 24, in <module>
    ImportError: cannot import name Named_Texture

Re-installing pyglui with "git submodule update --remote" fixes that problem.  But then I get failures due the bundle.spec file not adding various scipy modules (starting with cython_blas):

    % ./pupil_capture
    ...
      File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy/linalg/_decomp_update.c:35835)
    ImportError: No module named cython_blas

By adding around a dozen modules to the spec file, I can get to the point where I hit some new problems, apparently due to pyinstaller not understanding some of the dynamic imports used by billiard, as mentioned in https://github.com/celery/billiard/issues/120 .

A quick check suggests that the same problems seem to occur in the tagged "v0.6" version.

Given how many problems I've run into, I'm wondering: Is deploy_capture supported on the mac?

**Comment by mkassner** [comment]
We use deploy capture and deploy player to create the bundles. Since pyinstaller does not cross compile the scripts need to work on mac/linux/windows. 

However this process is quite finicky. I literally spent  weeks getting everything to bundle and run on all three platforms and we still have small problems that we solve when packages require upgrade or dependencies are added. So adding documented user support for bundling is hard to support and user problems almost impossible to debug. 

For example we use a custom version of billiard (https://github.com/mkassner/billiard) and the development version of pyinstaller.

Below a pip freeze of my bundle environment:
```shell
Cython==0.22
PIL==1.1.7
PyInstaller==2.1.1dev-9d0e0ad
PyOpenGL==3.0.2
altgraph==0.12
av==0.2.4
billiard==3.3.0.6
distribute==0.7.3
ipaddress==1.0.14
macholib==1.7
mercurial==2.7.2
modulegraph==0.11
nose==1.3.0
numpy==1.7.1
psutil==2.2.1
pyglui==0.4
pyre==0.2
pyzmq==14.7.0
scipy==0.12.0
uvc==0.2
wsgiref==0.1.2
```

So its doable and we use it for every release but yes setting it up so its portable is tricky.

You have three options:
 - Figure out a setup that bundles
 - Sent me a link to a fork and I'll check it out, bundle and send it to you (if you just need a recent version of the main repo bundled, raise an issue and Ill bundle and release within 24h.)
 - Use the runtime plugin-loader and a recent release bundle to customise your app. (the plungin loader will work in the bundle version just as it does when running from source. )


 BTW: The pyglui submodule update workflow should be fixed now.

**Comment by steven807** [comment]
Thanks for the info -- I'll try making a plugin.  I'll just suggest that there be a big fat README in the deploy directories, mentioning that they are not intended to be used by end users for the reasons mentioned above.

**Comment by mkassner** [comment]
Good Idea. I have added a README.
