### ISSUE TITLE
Different fixation numbers in different versions of Pupil Player

### ISSUE THREAD

**Issue by mihaelataranu** [pupil-labs/pupil#2094]
Hi, 
I have some older recordings that I am looking again at and I am not able to reproduce the same number of fixations for a video under different versions of Pupil Player. I want to recreate an export I did with version 1.19.2 (see screenshots of the excel files) into v.2.5.0. 
I am not sure why in the newest version of Pupil Player, when I upload the old recording and specify the same min, max duration and max dispersion I get different fixation numbers.

Also,  the eye confidence on the uploaded video/files is constantly 0.00. In the older exported pupil_position.csv file, I have higher eye confidence numbers also. Do you have an idea why could this be due to?

<img width="1121" alt="Screenshot 2021-01-28 at 10 12 14" src="https://user-images.githubusercontent.com/7983736/106118166-1b69d580-6154-11eb-911b-1f1d0abe54f2.png">
<img width="1590" alt="Screenshot 2021-01-28 at 10 13 04" src="https://user-images.githubusercontent.com/7983736/106118185-202e8980-6154-11eb-93ef-3a29ebcdb759.png">

**Comment by papr** [comment]
Hey,

I checked and there was a small change in the 2.0 release that can have an effect on detected fixations:

We removed the custom confidence threshold (default: `0.75`) in favor of the application-wide "minimum data confidence" (default: `0.6`, can be adjusted in Player's general settings). Reference:
https://github.com/pupil-labs/pupil/commit/e9e535c4da6d19be1ab8ab3f298149288f0c7827#diff-b2d45c5da6bfdf8f5a21b7da5fde92752a91e585a44111abb7eb0f4a291258c9

Starting in Pupil 2.0, we run 2d and 3d detectors in parallel. The confidence graphs only show 2d confidence. Since your recording was recorded pre Pupil 2.0, it only contains 3d data. Therefore, there is no 2d confidence in the prerecorded data. You can run the post-hoc pupil detection to get both, 2d and 3d data.

**Comment by mihaelataranu** [comment]
As my recordings were done in v1.19.2, I downloaded the version from your list of releases and tried to open my old files in that way. But I get the feedback: "Invalid recording: This recording requires Player version >= 2.0!" Is the post-hoc pupil detection the only way we will be able to get the 2D data graphs? (and that no old files recorded with versions < v.2.0 can be opened in their original recording versions?). Thanks for helping out:)
