### ISSUE TITLE
How to receive data and frames at the same time?

### ISSUE THREAD

**Issue by WilliamBTT** [pupil-labs/pupil#2121]
Hello everyone! 
If I have a tcp connection, how can I receive the frames from the cameras and the data from the pupil at the same time?

I have this code, but I get a UniDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte.

```py

import zmq
from msgpack import loads


addr = '127.0.0.1'  # remote ip or localhost
req_port = "50020"  # same as in the pupil remote gui
context = zmq.Context()
req = context.socket(zmq.REQ)
req.connect("tcp://{}:{}".format(addr, req_port))
req.send_string('SUB_PORT')
sub_port = req.recv_string()
sub = context.socket(zmq.SUB)
sub.connect("tcp://{}:{}".format(addr, sub_port))

def conexion_pupil():
    global control

    if control == 0:
        sub.setsockopt_string(zmq.SUBSCRIBE, 'frame.world')
        
    elif control == 1:           
        sub.setsockopt_string(zmq.SUBSCRIBE, 'pupil.')
    
    topic = sub.recv_string()
    if topic == 'frame.world' and control == 0:
        print("Received: " + topic +" ==> Next reception: pupil.eye")
        control = 1
        
    if topic == 'pupil.0.2d' and control == 1:
        print("Received: " + topic +" ==> Next reception: frame.world")
        control = 0
        
    msg = sub.recv()
    msg = loads(msg)


control = 0 # if control==0 I receive frame.world.   If control==1  I received pupil.0.2d

a = 1
while a < 1000:
    conexion_pupil()
    a= a + 1
```

**Comment by WilliamBTT** [comment]
Sorry for the insistence. Does anyone know how I could fix it?

Greatings and thanks.

**Comment by papr** [comment]
@WilliamBTT Apologies for the delayed response.

The issue is that the Frame Publisher sends three ZMQ frames (topic, msgpack-encoded meta data, image binary data) instead of the usual two (topic, msgpack encoded message).

Instead of receiving all available frames, you recv() only twice. I recommend using these helper functions https://github.com/pupil-labs/pupil-helpers/blob/master/python/recv_world_video_frames.py#L39-L60
