### ISSUE TITLE
Running pupil from source fails with cython

### ISSUE THREAD

**Issue by TheZadok42** [pupil-labs/pupil#2177]
Here is the full [output](https://pastebin.com/N7qtEgQm)  
Here is the cython [log](https://pastebin.com/xaKb7Dyd)

System info:  
```
# uname
Linux tzlap 5.13.5-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 25 Jul 2021 18:03:00 +0000 x86_64 GNU/Linux

# cat /etc/*-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
[lswh](https://pastebin.com/uVpTTJeJ)

**Comment by papr** [comment]
Hi, from what I can see in the full log, pyzmq is crashing on a [very low level (`Assertion failed: ok (src/mailbox.cpp:99)`)](https://github.com/zeromq/libzmq/blob/master/src/mailbox.cpp#L99). I suggest running the https://github.com/zeromq/pyzmq tests to make sure that this issue is not related to your pyzmq installation. I will close the issue since this seems not related to how we use pyzmq in Pupil Core.

Please be aware that we officially only support
- Ubuntu >=16.04
- macOS >=10.14
- Windows 10
