### ISSUE TITLE
Cannot activate export pupil positions in Pupil Player

### ISSUE THREAD

**Issue by qalhata** [pupil-labs/pupil#2236]
Hi, wonderful pupil labs folks,

I am struggling to understand why I can't activate the pupil positions option in pupil player (v 3.5.1)

Context:
- Data captured with pupil invisible
- Downloaded data from the cloud to create AoI surfaces in pupil player ( I know the cloud does enrichments - just want to build my own pipeline from pupil player.
In any case, can someone signpost me to what I am missing?

Surfaces, videos etc export just fine but no fixations csv and no pupil_positions csv ( I really want to use pupil diameter in my analysis)

Fixations export fine from the pupil invisible cloud download but not from the pupil player - I know the player was developed for core but I could do with the abovementioned csv, please. I'd like to export fixations and pupil_positions as part of the player software data export

Any advice on how to turn these on so they export OK?

![image](https://user-images.githubusercontent.com/15788219/167909020-7cca2dcd-205b-4cf6-a04d-237eef7fd662.png)

**Comment by papr** [comment]
Hi @qalhata 

Please be aware that eye videos recorded by Pupil Invisible are not suitable for pupil detection due to the off-axis location of the eye cameras. The pupils are barely visible most of the time. As a consequence, there is no `pupil_positions.csv` file.

Note, that Player's fixation detection algorithm does not perform well on Pupil Invisible data. Please use [Pupil Cloud's fixation detector](https://docs.pupil-labs.com/invisible/explainers/data-streams/#fixations) instead.

Best,
Pablo

**Comment by qalhata** [comment]
Thanks, @papr . Much appreciated
