### ISSUE TITLE
LSL folder is either nonexistent or not checked out

### ISSUE THREAD

**Issue by Isastol** [pupil-labs/pupil#2332]
Hi everyone,

I'm trying to install LSL according to the tutorial (https://ws-dl.blogspot.com/2019/07/2019-07-15-lab-streaming-layer-lsl.html). I especially need AMTI forceplate and BrainProducts. I get the error message "LSLAPPS_BrainProducts was enabled, but its folder is either nonexistent or not checked out" everytime I try. 

Has someone an idea whats the problem? My installation was complete according to the tutorial to this point.

Thanks and best regards,
Isabel

**Comment by mikelgg93** [comment]
Hi @Isastol, 

This issue seems to be related to Brain Products and not to Pupil Capture/Player or Service. For general inquiries, you can ask at our [Discord Channel](https://discord.com/channels/285728493612957698/285728493612957698), but you may have more luck inquiring directly to BrainProducts, at the [LSL Slack channel](https://join.slack.com/t/labstreaminglayer/shared_invite/enQtMzA2NjEwNDk0NjA5LTcyYWI4ZDk5OTY5MGI2YWYxNmViNjhkYWRhZTkwYWM0ODY0Y2M0YzdlZDRkZTg1OTUwZDU2M2UwNDgwYzUzNDg) or at their [repo](https://github.com/sccn/labstreaminglayer).

Best Regards,
Miguel
