### ISSUE TITLE
Pupil Player crashes on Mac when uploading Eye Video Overlay

### ISSUE THREAD

**Issue by fwalker89** [pupil-labs/pupil#234]
Dear all,

Pupil Player, version 0.6-112, crashes on my MacBook Air when I try to upload the plugin "Eye Video Overlay".

Any suggestions?

Thank you,
Francesco

**Comment by willpatera** [comment]
Hi @fwalker89 Yes, this is a bug. I have replicated on a MBAir running OS 10.11.1. Running from source I do not encounter any errors. This has either been fixed already in commits after the release, or is an issue related to bundling. We will get back to you on this shortly.

**Comment by willpatera** [comment]
This looks to have been fixed with [this commit](https://github.com/pupil-labs/pupil/commit/3470d71ffb1d157a5abd5cc7f05f9f585a610548) -- Is this correct @mkassner ?

@fwalker89 A quick workaround (while we are fixing this issue) is to use the previous version of [Pupil Player](https://github.com/pupil-labs/pupil/releases/tag/v0.6). I can confirm that `eye video overlay` works well in that context.

**Comment by mkassner** [comment]
Hi,

yes this was fixed recently. I ll bundle and release later this week.

**Comment by fwalker89** [comment]
Great! Thanks
