### ISSUE TITLE
3D Calibration: binocular support

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#271]
add second eye.

**Comment by willard-yuan** [comment]
Hi, @mkassner @patrickFuerst . I'm reading the code of calibration. In the file of [calibrate.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/calibrate.py#L301), I notice the position has the **norm_pos** key. Does the coordinates of `pupil_pts` and `ref_pts` are normalized by the image width and height, respectively?

By the way, would you like to send a `cal_pt_cloud.npy` to me so that I can make fully understand the process of calibration by it?

**Comment by cpicanco** [comment]
Any file will do?

[cal_pt_cloud.npy.zip](https://github.com/pupil-labs/pupil/files/69891/cal_pt_cloud.npy.zip)

**Comment by willard-yuan** [comment]
I'm really appreciate for your help. Thanks.

**Comment by cpicanco** [comment]
@willard-yuan , please, note that this file was generated by me with the screen marker calibration method and a monocular eye tracker.

**Comment by willard-yuan** [comment]
@cpicanco, for each item in array `cal_pt_cloud`, it consists of `(pupil_x/capture_width, pupil_y/capture_hight, ref_x/world_width, ref_y/world_hight)`, the `capture_width` is the eye image width and the `world_width` is the world image width. Is it right for understand the meaning of values in `cal_pt_cloud`?

**Comment by cpicanco** [comment]
@willard-yuan I am not sure, sorry about that. I would recommend you to use the pupil discuss google forum for data related questions or to create a new issue with "question: [your question]" in the title for this.

**Comment by willard-yuan** [comment]
Thank you for your advice.

**Comment by willpatera** [comment]
@cpicanco - thanks for supplying sample data and for the feedback here :)

Hi @willard-yuan each array in `cal_pt_cloud` is composed of arrays consisting 4 values each:

```
[pupil_x, pupil_y, reference_x, reference_y]
```

The coordinates for pupil positions and reference positions are in normalized coordinates. For more info on coordinate systems please see [data format](https://github.com/pupil-labs/pupil/wiki/Data-format#coordinate-systems) on the wiki. 

The pupil position and reference positions are temporally correlated using the `preprocess_data` utility function in `calibrate.py`.  

If you have more questions, please raise them here, otherwise close the issue :smile:

**Comment by willard-yuan** [comment]
@willpatera , I'm really appreciate for the full document of the data format. It's very helpful  for me. The coordinate is normalized by the method in [methods.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/methods.py#L461) in line 461:

```python
def normalize(pos, (width, height),flip_y=False):
    """
    normalize return as float
    """
    x = pos[0]
    y = pos[1]
    x /=float(width)
    y /=float(height)
    if flip_y:
        return x,1-y
    return x,y

def denormalize(pos, (width, height), flip_y=False):
    """
    denormalize
    """
    x = pos[0]
    y = pos[1]
    x *= width
    if flip_y:
        y = 1-y
    y *= height
    return x,y
```
Is't right?

**Comment by willpatera** [comment]
@willard-yuan -- correct, this is the normalize function that is used (and denormalize function to go back to pixel space). If you're using screen based marker calibration then the normalization of the marker position happens on [L29](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py#L290) in `screen_marker_calibration.py`

**Comment by willard-yuan** [comment]
@willpatera Thank for your great help. @mkassner Please close the issue as I have no permission to close the issue. Thanks.

**Comment by willpatera** [comment]
@willard-yuan -- The issue should remain open until binocular support for 3D calibration is implemented. 

I believe it is my mistake for suggesting closing above once resolving your question -- apologies.

**Comment by willard-yuan** [comment]
It doesn't matter.

2015-12-28 22:45 GMT+08:00, Will <notifications@github.com>:
