### ISSUE TITLE
Pupil with different cameras

### ISSUE THREAD

**Issue by matrejek** [pupil-labs/pupil#278]
I am using windows version with self-made tracker. It consists of two cheap cameras. I experience situations like:
- Windows 8.1 - app crashes when I start calibration
- El Capitan - windows are being closed right after I select camera

Are there any logs I can provide?

**Comment by willpatera** [comment]
Hi @matrejek - A few general questions:
  1. Cameras - What cameras are you using?
  1. Source or Bundle - Are you running from an application bundle or from source? If running from an application bundle, please list the version(s) you have tried. 
  1. Fork - I looked to see if you made a fork of pupil so that I could see changes you made to source code to accommodate cameras (and if any other changes). If you are running from source, having a look a a fork would really help us debug your issue. If you have a fork, could you please share a link?

_MacOS_ I am running MacOS 10.11.2 (El Capitan) on MacBook Air 11" (Early 2014). I can report that Pupil Capture is running smoothly when running from source and from the (latest release bundle for Mac)[https://github.com/pupil-labs/pupil/releases/tag/v0.6.22] using Pupil hardware. Your description leads me to believe that the issue is directly related to your cameras. It would not be possible for me/us to recreate your error without your specific hardware setup, but as stated above, having a look at a fork might help us to debug :smile: 

_Windows_ Again, I feel that the issue is hardware (camera) specific, but I will summon @MichaelBarz to this issue for a second opinion.

**Comment by matrejek** [comment]
Hi, running from bundle, lastest available for both platforms. My tracker is made from cheap cameras like that https://www.evertek.com/viewpart.asp?auto=42717&cpc=RECOM 
The eye camera was modded as your manual stated. I see also that pupil is being detected on Windows in eye preview. 

In the logs I can see:
World Process: 2016-01-06 17:29:39,063 - video_capture - ERROR - No accessible device found that matched ['Pupil Cam1 ID2', 'Logitech Camera', '(046d:081d)', 'C510', 'B525', 'C525', 'C615', 'C920', 'C930e']

I think that I will fork now and try make my cameras usable for the software. As you probably have better understanding of architecture - is it possible to succeed that way?

**Comment by willpatera** [comment]
The first step would be to check if your world camera is UVC compliant. If so, then you could proceed to add your camera to the [list in main.py](https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/main.py#L93).

**Comment by cpicanco** [comment]
Things you should know:

- Pupil uses its own fork of the C libuvc library for multiplatform compatibility (https://github.com/pupil-labs/libuvc).
- For python integration, Pupil wrote a Cython pyuvc binding for the libuvc library.
  - Please take a look at known issues of pyuvc (maybe libuvc issues, I am not sure): https://github.com/pupil-labs/pyuvc/issues
  - For an example of a cheap uvc compatible camera please take a look here: https://github.com/pupil-labs/pyuvc/issues/10;
- Earlier releases of Pupil used pyv4l2 instead (that offer better Ubuntu compatibility to the best of my knowledge, I am not sure if it would be the same with osx). With my hardware, the last working commit of pyv4l2 and dependencies can be found here: https://github.com/cpicanco/validation_project

**Comment by matrejek** [comment]
It looks like camera is not UVC compilant. I will consider rebuilding the hardware part. Thx for help and I will close it now.

**Comment by matrejek** [comment]
Hi, just wanted to ask one more question in this thread as I am back in this topic. 

Tried to read the code but I am not sure if both cameras has to be UVC compiliant or only the world one has to be?

**Comment by mkassner** [comment]
Both cameras beed to be UVC compliant to be used with the default video backend.
