### ISSUE TITLE
[Windows] World Camera: Could not set up capture device: Error code 32

### ISSUE THREAD

**Issue by FKlauke** [pupil-labs/pupil#281]
Hi,

I have an issue with the world cam:
When I start Pupil Capture or switch the world cam to pupil cam 1, the programme tells me that the "Capture device does not support preferred frame-rate 24" and falls back to fake capture. It concludes that it "Could not setup capture device. Fall back to Fake Capture. **Error code: 32**". I get the same result when I ask the world cam window to access the integrated cam (eye cam).
I consistently got this error message on two **Windows 7** computers and one **Windows 10** computer (also tried Win8 compatibility mode), and with **application bundles v0.6.18 and v0.6.9** (did not try this one on Win10, though).

Any help or recommendation would be highly appreciated :)

Thanks,
Fabian

**Comment by tnoz** [comment]
Hello, 

I'm having the same issue. 
I recently bought a headset with a high-speed world camera and a 120hz eye camera, and with single USB connector. 
When I start Pupil Capture on a Windows 7 laptop, both cameras works. 
But on another Windows 10 laptop which I'd like to work on with Pupil, the world camera fails with the same error messages reported by Fabian. 

I've confirmed that the world camera (Pupil Cam1 ID2) is recognized on the Device Manager and is working with a webcam capturing freeware. 

On the correctly-working Win7 laptop, the world camera is recognized with settings of Resolution: 1280x720 pixels and Frame rate: 60fps (or 9.00000095367 is another available option), so I thought it might work if I can specify the frame rate as 60. Since the framerate field doesn't seem to become available until the camera is recognized correctly, I copied a binary setting file c:\Users\<user_name>\pupil_capture_settings\user_settings_world from the working Win7 laptop to the non-working Win10 laptop, but Capture still fails on recognizing the world camera.

Solutions/workaround would be much appreciated!
Taka

**Comment by amirostal** [comment]
Hi, 

I'm having the same issue with my new headset, on a Win7 machine.
Did a solution come up? Or any other progress on this since January? 

Thanks very much, 
Amir

**Comment by cpicanco** [comment]
@mkassner , @willpatera , any news about this one?

An alternative in the meantime is to use the Ubuntu version and stream Pupil data over the network.

Best,
Rafael

**Comment by mkassner** [comment]
This should be obsolete with the new backend.
