### ISSUE TITLE
Defining regions of interest on surface

### ISSUE THREAD

**Issue by fwalker89** [pupil-labs/pupil#302]
Dear all,
Can I manually define, in the Pupil Player, regions of interest (ROIs) for specific surfaces (i.e. defined by markers)? 

I would like to compare the heat-maps with my previously defined ROIs, to check how much these two match. If this is not possible, it would be a really nice implementation.

Thank you,
Francesco

**Comment by cpicanco** [comment]
Hi Francesco, how have you defined your ROIs (outside Pupil, correct)?
Could you give us an example?

**Comment by fwalker89** [comment]
Hi Rafael,

I'm analysing eye-movements on paintings. So, to give you an example, I expect that my subjects will focus on the face of the human figure, depicted in painting X. Thus, the face of the human figure is my ROI.
I define my ROIs before conducting any analysis, so indeed outside Pupil.

**Comment by cpicanco** [comment]
Do you mean real paintings or paitings presented in a computer screen? Some
alternatives varying in complexity:

You could produce different heatmaps along the recording (using the trim
marks to choose different sections) and produce a qualitative, time
sensitive, evidence based analysis through eye inspection. No new
functionality needed. Unfortunatelly, the section feature in Pupil Player
is yet underexpored. It means doing stuff manually.

The heatmap is a histogram with two dimentions. Each one  should have the
same size of your paintings. You could use the proportions of the paitings
to find the coordenates of the human body you want if you are using real
paintings. Than you could use those coordenates as the center of circles,
controling the diamenter as necessary, using them as ROIs. This would allow
a more quantitative approach.

Also, you could take advantage of the already implemented perspective
transformations of the pupil surfaces in order to work in a standard space
to visualize and analize the resulting data.

Not sure if detecting the faces is an option. There are some OpenCV
functions to that end. Maybe too much work for what you want.

Hope this helps,
Rafael

**Comment by fwalker89** [comment]
Thanks for the great suggestions! Especially your first solution sounds pretty straight forward. I'll give it a try asap. By The way I'm analysing real paintings, displayed in a museum.

All the best!
Francesco

**Comment by mkassner** [comment]
I think this can be closed.
