### ISSUE TITLE
screen capture plugin?

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#310]
Is this something we may want?

I could imagine selecting screen as the capture device in a separate instance of pupil capture.

or

capture the screen via a plugin. Maybe this is better. Could still run in a separate instance...

I can invoke screen capture on my mac by:
ffmpeg -f avfoundation -i 3:0 -r 30 -vcodec mpeg4 out.mp4
3:0 (video capture 3 (on my device that is the screen), audio capture 0)

on linux we would your x11grab

**Comment by cpicanco** [comment]
Screen as a device makes sense for me when:
a) the world camera is not necessary;
b) you want the mouse pointer controlled by your eyes;
c) ideal for assistive applications.

On the implementation, I would vote for a plugin.

**Comment by fneitzel** [comment]
I think it is necessary for VR environments.

I'd like to choose it as capture device instead of a plugin.
So maybe it is a 'Fake Capture Device' ?

**Comment by willpatera** [comment]
@mkassner - Yes, it is a good idea and I think `screen capture` should be a plugin.

`screen capture` as plugin - I think we have more flexibility if we add `screen capture` as a plugin. Because one may want to be able to switch the `capture device` while simultaneously capturing the screen. In addition to @cpicanco's and @fneitzel's use cases another - perhaps overly obvious - one is to is to record demos for documentation :smile:    

While  `screen capture` as a `capture device` seems to initially make sense from a  user perspective, it would be limiting if one wants to capture the screen **and** record the screen. Additionally, it in this scenario, the top level menu `Camera Settings` would no longer be accurate if it contains a non-camera device (I guess renaming is an option, but again, the plugin route IMHO is better as stated above).

**Comment by cpicanco** [comment]
I think it is related to:
https://github.com/pupil-labs/pupil/issues/164

**Comment by mkassner** [comment]
stale
