### ISSUE TITLE
Document dependencies in the README

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#404]
Recently the msgpack Python package has been added as a dependency.

It would be nice to document the list of dependencies (with the minimum version required, if applicable) in the README file. It is a good practice to do so for a free software, so that people can build it from source and create a package easily.

**Comment by willpatera** [comment]
@swilmet-ucl - I understand the desire/convention to have a comprehensive README file as an introduction to the repository, but I would prefer to keep the documentation of dependencies on the [wiki](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Linux) so that others can easily read and contribute without the need to make a PR to get their changes merged (anyone can contribute to the wiki 😄 )

**Comment by swilmet-ucl** [comment]
Ok, as you prefer.
