### ISSUE TITLE
Pupil Capture 0.8: process doesn't terminate

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pupil#409]
When I close a Pupil Capture window (version 0.8), the process doesn't terminate, I need to kill it with `Ctrl+C`. (On Linux).

It's a recent regression, I don't have this problem with version 0.7.6.

**Comment by mkassner** [comment]
Thanks for this report. 

It turns out the the shutdown procedure of zmq differs for recent versions and for OS's. I have not been able to reproduce your observation on Mac but I was able to trigger the error in Linux. After adding an explicit context termination in the world process and updated pyzmq/libzmq to the lasted releases I was not able to reproduce the error on my linux test machine. 

Could you do the same (update pyzmq and pupil) and try again?

**Comment by mkassner** [comment]
I m guessing this works for you? It works for us...

**Comment by swilmet-ucl** [comment]
Sorry for the late reply, I'm now back at my day job.

It now works fine for me too, the process terminates. Thanks for the quick response!

**Comment by mkassner** [comment]
great to hear!
