### ISSUE TITLE
Add offline Pupil Detection in Player

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#432]
Add a plugin that does off-line pupil detection in player.

**Comment by swilmet-ucl** [comment]
It would also be useful to do pupil detection from a video file (without the other data that Pupil Capture generates). So, a simple *.mp4 file, recorded with another program (because Pupil Capture doesn't support a lot of cameras).

See this discussion for more background on the use-case:
https://groups.google.com/forum/#!topic/pupil-discuss/j0l2w_q_esA
"Non-UVC camera (video grabber)"

**Comment by papr** [comment]
Will be fixed #715

**Comment by mkassner** [comment]
closed with #715
