### ISSUE TITLE
Missing original license

### ISSUE THREAD

**Issue by LeszekSwirski** [pupil-labs/pupil#440]
Hey everyone,

Great to see my work being used, I'm pleased it could be useful to someone! Could you however please make sure to include the original license/copyright (definitely https://github.com/LeszekSwirski/singleeyefitter/blob/master/LICENSE, I'm not sure if you also need https://github.com/LeszekSwirski/pupiltracker/blob/master/LICENSE.md or if the parts that remain from my original algorithm are a clean reimplementation). Also, if you have any interesting improvements and have the spare time, I'd love it if you could send some patches upstream.

Cheers.

**Comment by mkassner** [comment]
I actually made an issue specifically for this a while ago: #290 . (Sorry that it took an issue by the original author to revive it.) The omission was certainly not intentional ( We at least did not fail to reference your paper in the [release notes](https://github.com/pupil-labs/pupil/releases/tag/v0.7.4). )

We will add the MIT licence to all files that originated from (or carry parts of) https://github.com/LeszekSwirski/singleeyefitter and add references to the source. 

We are not using any source form  https://github.com/LeszekSwirski/pupiltracker/ as we had developed our own 2d detector a while ago. It does have an improved version of the centre-surround filter (inspired by the relevant paper) but that is a complete re-implementation.

I think there are a number of changes that could flow back upstream. They address the realtime nature of our system and things like slippage events so I m not sure if they are an improvement in a strict sense of rather a new feature. Lets discuss them in more detail if you want.

**Comment by LeszekSwirski** [comment]
Ah, sorry, I missed that issue otherwise I would have just pinged you on it. I'll close this one as a duplicate. No worries about forgetting it though, it's an easy thing to miss, and the paper reference is much more useful for me anyway. Let's talk about upstreaming offline (or in another issue).

**Comment by LeszekSwirski** [comment]
Duplicate of #290
