### ISSUE TITLE
Problem: Calibration plugins do not account for low confidence pupil data

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#447]
I remember that the pupil capture calibration routine just started if
I) the pupil is detected in the eye cam
II) the marker is detected in the world cam

In the moment the eye cams can be deactived/closed and the marker detection starts taking samples in the world cam while calibration is activated.

**Comment by papr** [comment]
Sorry that it took so long to answer. Could you specify the problem or question you are have?

**Comment by fneitzel** [comment]
The problem is that the calibration takes place even if the eye is not detected.

Why is the calibration processing if (just the world camera recognizes the calibration pattern and) no eye is detected?

**Comment by cpicanco** [comment]
Hi @fneitzel , how are you checking if the eye is in a "detected" state or not? Are you assuming this from closing the eye process and starting the calibration? As far as I know, something like a "is_detected" state is not implemented. The way pupil calibration works is by means of the "confidence", and it will send a "successful" ou "failed" result at the end. 

Regardless of it, egocentric setups, the ones that requires just the world process running, should not be allowed to start the calibration.

If you are concerned on how improve the calibration process, there is some discussing here:  #182

**Comment by papr** [comment]
@fneitzel and I talked about the issue. The behaviour he described was an implicit result of Capture's pupil detection threshold.

The calibration procedure waits for at least `n` eye samples. Earlier low confidence positions (this includes not detecting the pupil at all) would not be counted since they would be thrown away before reaching the calibration plugin. With the removal of the confidence threshold the calibration plugin would use all positions found (including ones with low confidence).

Future calibration plugins should account for this issue. I will rename this issue accordingly.

**Comment by papr** [comment]
Solutions: Add user option for confidence threshold to calibration plugins.

Enhancement: #463

**Comment by papr** [comment]
Wait, this should be already implemented: [`screen_marker_calibration.py#L262`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py#L262)

This might need more investigation than I thought.
