### ISSUE TITLE
Building fails with latest Eigen (3.3-beta2)

### ISSUE THREAD

**Issue by jampekka** [pupil-labs/pupil#449]
Building pupil_detectors fails with Eigen 3.3-beta2, which is currently the version in Debian unstable and testing.

```
pupil_src/capture/pupil_detectors$ python2 setup.py build_ext
...
In file included from /usr/local/include/eigen3/Eigen/Core:326:0,
                 from ../../shared_cpp/include/geometry/Ellipse.h:6,
                 from ../../shared_cpp/include/common/types.h:5,
                 from singleeyefitter/EyeModel.h:5,
                 from singleeyefitter/EyeModel.cpp:3:
/usr/local/include/eigen3/Eigen/src/Core/util/XprHelper.h: In instantiation of ‘struct Eigen::internal::promote_scalar_...
...
singleeyefitter/EyeModel.cpp:731:1:   required from here
/usr/local/include/eigen3/Eigen/src/Core/util/XprHelper.h:74:8: error: no type named ‘Literal’ in ‘struct Eigen::NumTraits<ceres::Jet<double, 6> >’
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Manually installing [Eigen3.3-beta1](http://bitbucket.org/eigen/eigen/get/3.3-beta1.tar.bz2) to `/usr/local/include` fixes this.

**Comment by willpatera** [comment]
I recently dealt with a related issue when re-installing dependencies on macOS 10.12.1. It seems that the "stable" version of `ceres-solver` was not compatible with `eigen` `v.3.30`.

I was able to resolve this issue by building `ceres-solver` from `HEAD` - `brew install ceres-solver --HEAD` and was able to successfully build pupil detectors. 

I will close this issue now as this issue seems to be `eigen` and `ceres-solver` related and not directly related to Pupil.
