### ISSUE TITLE
How to run Capture in the background

### ISSUE THREAD

**Issue by mothman1** [pupil-labs/pupil#455]
How can I run capture process in the background? I don't want to edit any of the capture settings, all I want is to run pupil capture and start recording. While recording, I don't want the user nor myself to edit any of the capture settings - Basically, I just want to run and record.

If it's not possible to just run it in the background, how can I stop displaying the frames stream for both world and eye cameras?

**Comment by papr** [comment]
Dear @mothman1 
Would it be sufficient for you if the UI would be minimised on start up? There is current no other way to hide the frames other than minimising the windows.

If you could elaborate on your exact use case I might be able to provide further help.

**Comment by mothman1** [comment]
I'm running the eye tracker on a non-powerful computer and displaying the frames affects processing time and number of fps. For example, the application starts with 30fps for both cameras but a minute later the number drops to as low as 5fps.

**Comment by papr** [comment]
*Pupil Capture* does not execute any UI functions while the according window is minimised. Please try to run your experiment again with the windows minimised.

In case that you still have performance issues afterwards I would suggest that the UI is not the problem. Possible other issues might be the pupil detection algorithm or a performance-hungry plugin. Are you using the 2D or 3D detector?

**Comment by mothman1** [comment]
This sounds good :) what about when no display monitor is attached, I mean when I run pupil labs without displaying it on a screen - Would this also mean no UI functions running?

**Comment by papr** [comment]
I do not think that this would work since Pupil Capture does not process if the window is visible. This could be done with
```c
int visible = glfwGetWindowAttrib(window, GLFW_VISIBLE);
```
Even if it would be implemented it would not be faster than minimising the windows. 

An additional performance improvement would be to not call the plugins `gl_display()` method (see [`world.py#L455-L456`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/capture/world.py#L455-L456)) if the window is minimised/iconifed.

This would break plugins that rely on a regular `gl_display()` call. Although, plugins should only rely on the `update()` method to be called constantly.

**Comment by mothman1** [comment]
This is great, thanks mate. I set g_pool.iconified to always be True for both world and eye for now.
