### ISSUE TITLE
Reading messages with msgpack-java

### ISSUE THREAD

**Issue by AugustoEst** [pupil-labs/pupil#510]
Can anyone share an example code of how to use msgpack-java to read Pupil's ZMQ messages (e.g., 'norm_pos')? This is quite straightforward in Python, but it has been a nightmare in Java.

**Comment by cpicanco** [comment]
Hi. I did this on free pascal. Since free pascal is a strong typed and an easy to read language, it may be useful for you:

Type to receive:
https://github.com/cpicanco/stimulus_control/blob/d73be4e484f37e2e10c1941575943b3a42fef5ba/units/zmq_client.pas#L24-L27

Each language may have its own specificities, for example, in free pascal it is necessary to set the position of the buffer before reading from it:
https://github.com/cpicanco/stimulus_control/blob/master/units/pupil_communication.pas#L264-L277
