### ISSUE TITLE
The newly released version for Windows 10 can not export 'gaze_positions.csv' and 'pupil_positions.csv'.

### ISSUE THREAD

**Issue by zhangyy985** [pupil-labs/pupil#550]

**Comment by willpatera** [comment]
Hi @zhangyy985 - thanks for the report. Can you provide more information so that we can resolve this issue? 

Can you please open the cmd prompt and then run `pupil_capture.exe` so that we can get some feedback from the logger? 

Can you send the info.csv file from the recording, or at the very least the capture used to make the recording from this file?

**Comment by zhangyy985** [comment]
Thank you for your reply.

I restart my computer. The export function works.

If I meet this problem again, I will upload related information.

I guess this program conflict with another program.

**Comment by willpatera** [comment]
Hi @zhangyy985 - that's relatively good news. I will close this issue now.
