### ISSUE TITLE
Windows: FPS graph does not show rates above 60fps

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#552]
A bit of investigation using the Bundle shows that:

 - The rate is in fact 120fps or at least twice that of 60 fps.
 - The exported timestamps in the raw_data export csv file show a low granularly as well as multiple frames with the same timestamps. 

My guess is that the time source under windows is not good enough. And this problem creates consecutive frames with the same timestamp. 

The fix need to happen in https://github.com/pupil-labs/pyuvc/blob/master/windows_time.pxi

My guess is that using something like https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx will solve this issue.

**Comment by mkassner** [comment]
Reading more on this subject, my repulsion to windows is only enforced. Without significant overhead the best we can do is 5ms resolution. Still better than 1/64of a sec we are getting right now on windows.

@willpatera  I have edited the file. When you have time could you rebuild+install pyuvc and rebundle?

**Comment by willpatera** [comment]
@mkassner - Thanks for the updates. I will rebuild & rebundle tomorrow AM.

**Comment by willpatera** [comment]
## pyuvc
I added `winmm` to the setup.py file and rebuilt the `pyuvc` wheel. I have also and uploaded the new wheel to the [pyuvc v0.9 release](https://github.com/pupil-labs/pyuvc/releases/tag/v0.9).

## pupil capture
I rebuilt, rebundled, and updated the download for [v0.8.7-w release](https://github.com/pupil-labs/pupil/releases/tag/v0.8.7-w)

I made a test recording with the Pupil Capture bundle on an Intel NUC running Windows 10 64 bit. 

Notes:
- FPS Graph - displays the correct FPS; aligns with the camera settings
- Timestamp accuracy - the timestamps align with the specified capture rate +/- 3 frames 
- Timestamp precision - timestamps still have unfortunately low precision 😞  - However this is the expected precision for the `timeGetTime` function as noted in your second comment. See Windows  [documentation](https://msdn.microsoft.com/en-us/library/vs/alm/dd757629(v=vs.85).aspx)

I am attaching a zipped folder with gaze_positions.csv, pupil_positions.csv, and the info.csv file(s) to this comment so that you can review. The recording was 1m 03s duration with world camera set at 60hz and a monocular eye camera at 120hz. 

@mkassner - please download and review the .zip attached.
[0-3776.zip](https://github.com/pupil-labs/pupil/files/656395/0-3776.zip)

**Comment by willpatera** [comment]
I am going to close this issue as it is resolved. All other issues related to pyuvc will be opened in the `pyuvc` repo.
