### ISSUE TITLE
Python2 / python3 dependencies

### ISSUE THREAD

**Issue by Lahorde** [pupil-labs/pupil#561]
On my system, python default version is python3. So started capture with :

    python2.7 main.py

I got these errors :
```
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.8.7.3
world - [INFO] world: System Info: User: remi, Platform: Linux, Machine: remi-hp9470m, Release: 4.7.10-1-MANJARO, Version: #1 SMP PREEMPT Sat Oct 22 19:15:11 UTC 2016
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    from Cython import cythonize
ImportError: cannot import name 'cythonize'
Process world:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/data/remi/Projects/eye_tracking/pupil_labs/pupil/pupil_src/capture/world.py", line 98, in world
    import pupil_detectors
  File "/home/data/remi/Projects/eye_tracking/pupil_labs/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from detector_2d import Detector_2D
ImportError: No module named detector_2d
```
Cython was previously installed using pip2. After installing Cython using pip3 I did not get Cython error.
In order to not mix python2 / python3 dependencies I set python2 as [default python](https://wiki.archlinux.org/index.php/python#Python_2)

But may be it would be better in pupil code to be sure all dependencies are looked for in python2 dependencies.

**Comment by willpatera** [comment]
@Lahorde - I think the onus should be on the developer to define their environment. In the _near_ future we plan to make pupil source code python2/python3 interoperable, so IMHO specifying a path for python2 would go against 2/3 interoperability.  

## Python3 branch
If you default to python3, you might want to check out the [`python3_opencv3_merged`](https://github.com/pupil-labs/pupil/tree/python3_opencv3_merged).

## Virtual Environment
Another option that I have found works nicely is to set up a virtual environment. I have a virtual environment (VENV) set up on my machine so that I can run python2 and python3 in nicely isloated environments. Install all python dependencies in your VENV and activate the VENV before running Pupil. 

Here are some references that my be of use to you:
- [Virtualenv](https://virtualenv.pypa.io/en/latest/) 
- If you use fish shell instead of bash you can use [virtualfish](http://virtualfish.readthedocs.io/en/latest/)

**Comment by Lahorde** [comment]
Thanks for useful suggestions.
