### ISSUE TITLE
Visualizers Crash - Windows v0.8.7-w-19 

### ISSUE THREAD

**Issue by todd-herbert** [pupil-labs/pupil#566]
Windows 10 x64

Following calibration, the calibration visualizer is shown, which crashes and forces the world window to be closed. 

Opening the debug visualizer from the eye0 window also causes a crash.

**Comment by willpatera** [comment]
@todd-herbert - which calibration routine?

**Comment by todd-herbert** [comment]
The software crashes after calibration when the visualizer appears with:
Screen Marker
Natural Features

The calibration crashes on initiation with:
Camera Intrinsics

The calibration crashes when detecting the first marker with:
Manual Marker


Here is the console output from each calibration.
[cameraintrinsics.txt](https://github.com/pupil-labs/pupil/files/678166/cameraintrinsics.txt)
[manualmarker.txt](https://github.com/pupil-labs/pupil/files/678167/manualmarker.txt)
[naturalfeatures.txt](https://github.com/pupil-labs/pupil/files/678168/naturalfeatures.txt)
[screenmarker.txt](https://github.com/pupil-labs/pupil/files/678169/screenmarker.txt)

**Comment by mkassner** [comment]
These are at least two different bugs. We will investigate in the first
week of Jan when everybody is back at work.

We will post updates and fixes.



On Dec 30, 2016 3:42 AM, "todd-herbert" <notifications@github.com> wrote:

The software crashes after calibration when the visualizer appears with:
Screen Marker
Natural Features

The calibration crashes on initiation with:
Camera Intrinsics

The calibration crashes when detecting the first marker with:
Manual Marker

Here is the console output from each calibration.
cameraintrinsics.txt
<https://github.com/pupil-labs/pupil/files/678166/cameraintrinsics.txt>
manualmarker.txt
<https://github.com/pupil-labs/pupil/files/678167/manualmarker.txt>
naturalfeatures.txt
<https://github.com/pupil-labs/pupil/files/678168/naturalfeatures.txt>
screenmarker.txt
<https://github.com/pupil-labs/pupil/files/678169/screenmarker.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pupil-labs/pupil/issues/566#issuecomment-269724811>,
or mute
the thread

**Comment by willpatera** [comment]
Hi @todd-herbert - I have made some changes and re-bundled Pupil Capture for windows `v0.8.7-w-20`. Please [download here](https://github.com/pupil-labs/pupil/releases/tag/v0.8.7-w#downloads) and test.

**Comment by todd-herbert** [comment]
The bugs in manual marker and camera intrinsics routines appear to be gone.
The software still crashes when the visualizer appears after Screen Marker, Manual Marker and Natural Features routines.

![crash](https://cloud.githubusercontent.com/assets/24772776/21598034/68b57e2c-d1b9-11e6-861c-70afcb93a0aa.gif)


[naturalfeatures.txt](https://github.com/pupil-labs/pupil/files/681536/naturalfeatures.txt)
[screenmarker.txt](https://github.com/pupil-labs/pupil/files/681537/screenmarker.txt)
[manualmarker.txt](https://github.com/pupil-labs/pupil/files/681538/manualmarker.txt)

**Comment by willpatera** [comment]
Hi @todd-herbert - thanks for the update and screen capture. 

Unfortunately I am not able to replicate your issue with the current bundle `v0.8.7-w-20` on my Windows 10 development machine. 

## Debugging
Could you please do the following:
1. delete pupil_capture_settings folder in your home directory
1. open the Pupil Capture folder
1. Open command prompt within that folder
1. In command prompt type `pupil_capture.exe` (this will launch the executable and the command prompt will stay open if the program crashes)

Send the output from the command prompt if you get experience another crash. 

## Computer
Another thing that I notice from your screen capture is that the FPS is very low. On our development machine (Intel NUC) FPS remains at around 30fps or greater during calibration. Can you share your machine specs. 

## Pupil headset
I see that you are using a DIY headset with the C525 camera. Can you share specs of your headset as well?

**Comment by todd-herbert** [comment]
**Debugging:**
After following the steps the same problem occurs.
[output.txt](https://github.com/pupil-labs/pupil/files/681791/output.txt)

**Computer:**
During calibration the program tends to sit at around 12fps on this machine.

![specs](https://cloud.githubusercontent.com/assets/24772776/21601340/46125112-d1ee-11e6-81a5-2234b7523e57.PNG)

**Headset:**
The Headset has a Logitech C525 world cam, Microsoft HD-6000 eye cam, and attaches through a usb hub. It is built as per the guide at https://github.com/pupil-labs/pupil/wiki/DIY-Kit-Guide

**Comment by todd-herbert** [comment]
On a potentially related note, opening the debug visualizer from the Pupil Detector 3D section of the Eye Window causes a similar crash with no relevant output. 

![debugcrash](https://cloud.githubusercontent.com/assets/24772776/21601498/3f7e8fee-d1f0-11e6-94bd-a778b1b35f7a.gif)
