### ISSUE TITLE
replace current camera distortion model with fisheye model

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#605]
its all in the `cv2.fisheye` namespace.
Note that using a recent version of opencv is highly recommended for some bugfixes like:

https://github.com/opencv/opencv/pull/6454

**Comment by papr** [comment]
Am I correct that [`camera_intrinsics_estimation.py`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py) is the place to apply these changes?

**Comment by mkassner** [comment]
Yes. But also all occurrences of distort and undistort in the codebase

**Comment by Tobias-Fischer** [comment]
Hi @papr @mkassner @marc-tonsen,
Do you have any news on this issue? I'd be happy to contribute.

Best, Tobias

**Comment by marc-tonsen** [comment]
Hi @Tobias-Fischer !

I have created a PR #789 that includes a draft of how the fisheye camera model can be incorporated into Capture. Implementing this functionality is a bit messy because the cv2.fisheye module is buggy and requires extra code to deal with the bugs. Also I had to change the way the camera intrinsics are accessed in Capture, respectively the way the functionality dealing with lens distortion is accessed. As you can see in the PR I have introduced _camera model objects_ that encapsulate this functionality.

The parts of the code dealing with surface tracking have not been correctly updated yet, so they do not work in this PR. I will try to this soon. Camera calibration and gaze mapping is open for testing!

Best,
Marc

**Comment by mkassner** [comment]
closed with #789
