### ISSUE TITLE
URGENT: Pupil Player crashes instantly when importing recordings, on OS Sierra 10.12.3

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#622]
Hi all,

I have a problem with playing and post-processing the recordings in Player on a Mac Book Pro OS Sierra 10.12.3, and unfortunately need a solution ASAP. 

Specifically, as soon as a recording directory is dropped onto a Player window, the Player crashes. I am not a Mac user, so I do not know how to run it from the source, nor how to visualize the error but it seems similar to the issue #598 (https://github.com/pupil-labs/pupil/issues/598). The issue #598 has been closed but I could not see the solution to Player crash in the thread. Could you please tell me how this could be fixed?

My apologies for the urgency.

Ogi

**Comment by willpatera** [comment]
Hi @ogik13 - This issue has been fixed as @papr noted in the [issue comment](https://github.com/pupil-labs/pupil/issues/598#issuecomment-275334875). However we have not yet released a `macOS` bundle that incorporates this fix. So at current you would either need to run from source to get this fix or wait to get the bundle when it is released. 

If your issue is not the same as #598 - you can upload a sample video and send/post the link so we can test and debug.

**Comment by ogik13** [comment]
Thank you for the quick reply, Will. I think we will try running it from the source.

**Comment by willpatera** [comment]
@ogik13 - did you have a chance to run from source yet?

**Comment by ogik13** [comment]
Hi Will,

No, I haven't. We did not have enough time to install the software and
Python. I will update you in case we decide to run it from the source.

**Comment by mkassner** [comment]
I think this is fixed with v0.9.5
