### ISSUE TITLE
Finally make the v0.9 mac bundles

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#671]
Users need the new bundle: #667

**Comment by uncflorians** [comment]
Did anyone made the macOS bundle work, right away from downloading it? What do I have to consider when I try to run the applications from the bundle?

**Comment by cpicanco** [comment]
It should work out of the box with pupil cameras.

**Comment by uncflorians** [comment]
I am running os 10.12.4 and non of the applications would even show up after I start it. It just crashes. Do I need anything else, than the bundle?

**Comment by papr** [comment]
Did you get the permissions dialogue? macOS asks for your permission to open an app that you have recently downloaded. This could be the reason why the app does not even show up at all, because it was never actually started.

**Comment by uncflorians** [comment]
Yes I did get the permission dialogue and I started the program with right-click > open. That is all right, but afterwards it crashes.

**Comment by papr** [comment]
There should be log files in your user settings folder `~/capture_user_settings` (i believe)

**Comment by uncflorians** [comment]
There is no such folder. Meanwhile I tried to load all dependencies and install it via command line.
There if I try to start pupil player by cd.../player python main.py

I get the following error

python main.py
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from multiprocessing.spawn import freeze_support
ImportError: No module named spawn

**Comment by uncflorians** [comment]
I really like pupil labs but it is difficult for a programming noob to catch up with your explanations. Even more difficult if your releases do not work. Have you tried it on a neutral mac? I mean a machine with no dependencies installed or whatsoever, no programmer's machine.

**Comment by papr** [comment]
You need to run python3 main.py

**Comment by cpicanco** [comment]
There was a problem with pyinstaller blocking mac releases (maybe still unsolved?).

**Comment by papr** [comment]
And please run open -a path/to/capture.app from the terminal. This will hopefully show some kind of logs.

**Comment by uncflorians** [comment]
If I run python3 main. py : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /usr/local/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    from file_methods import Persistent_Dict, load_object
  File "/Volumes/Macintosh SSHD/florianschertenleib/libuvc/pupil/pupil_src/shared_modules/file_methods.py", line 16, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

@papr:

open -a PupilCapture.app
LSOpenURLsWithRole() failed for the application /Applications/PupilCapture.app with error -10810.

**Comment by mkassner** [comment]
I this issue has been hijacked by anther topic. Since we did release new mac bundles. I will close this now.
