### ISSUE TITLE
Access to the Video-stream

### ISSUE THREAD

**Issue by tunazhao** [pupil-labs/pupil#691]
Hello,
I am trying to get access to the video stream of the front camera of the eye-tracker. I am working on Processing. Is there a way to do it?

**Comment by mkassner** [comment]
Hi,

do you mean to access the data via the network or from the eye tracker directly?

**Comment by tunazhao** [comment]
Not the data, we need real-time video stream from the eye-tracker directly

**Comment by papr** [comment]
Dear @tunazhao 
You can talk to the cameras using `libuvc`. You will probably need java-bindings for it since Processing is java-based. A quick search resulted in https://github.com/saki4510t/UVCCamera (Java for Android, probably transferable to normal Java) and https://github.com/CyberCastle/jLibuvc (direct lib bindings).

**Comment by tunazhao** [comment]
Thank you very much. I will check the links.
