### ISSUE TITLE
timestamp missmatch

### ISSUE THREAD

**Issue by uncflorians** [pupil-labs/pupil#696]
Hi there, 

I recognized that annotation timestamps do not correspond with the timestamps noted down in pupil_positions.csv. I would assume that each annotation inherits the timestamp of the corresponding frame.
How can that be?
Ideally, the annotations would be included in pupil_positions.csv.

Best,
Florian

Edit: I attached two export files, non of the timestamps in one of the files corresponds with any of the timestamps in the other file.
[annotations_pupilpositions.zip](https://github.com/pupil-labs/pupil/files/908135/annotations_pupilpositions.zip)

**Comment by papr** [comment]
Dear @uncflorians 
I just had a look at your uploaded files.

The annotation timestamps range from `3941.781323662` to `3962.861623076`.
The pupil positions range from `3941.76832099` to `3972.632680691`.

> annotation timestamps do not correspond with the timestamps noted down in pupil_positions.csv

They look very corresponding to me. Could you clarify would you meant with your statement? Maybe I misunderstood you.

**Comment by papr** [comment]
Dear @uncflorians 
is this still an ongoing issue?

**Comment by uncflorians** [comment]
Sorry, I didn't recognize the comment.

I actually assumed that the precise timestamp of an annotation can be found for a frame in pupil positions. That is not the case.  There is a timestamp 3941.781323662 in annotations but not in pupil positions. 

That's what I meant.

**Comment by papr** [comment]
Player annotations—i.e. annotations that are created in Player—get actually the timestamp of the current frame. Capture annotations get the timestamp of their creation which does not correspond necessarily to the last frame's timestamp. This is important since annotations can be created remotely using Pupil Remote. Assuming last frame's timestamp would make the annotation as a measurement simply imprecise.

`g_pool.timestamps` contains the list of all timestamps. Searching this sorted list for the closest timestamp is very efficient (*O(log n)*). The closest timestamp can be converted to a frame index and from there to any other possible information in Pupil Player.

**Comment by uncflorians** [comment]
Perfect, thank you for that information!
