### ISSUE TITLE
Memory overflow and the marker detector cacher

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#703]
Hi,

I have an old issue related to the detector cacher and a custom plugin. Right now, data (detected markers) must be copied during multiprocessing to be saved only at the end, when all markers were detected. I am not sure why the robust detection fn does not fail with memory overflows and I am guessing that this function is doing both detecting and somehow taking care of the memory. I am using another function instead (for my screen detector), and after msgpack changes (that prefers python types) memory consumption is stratospheric. I was reading the following issue http://stackoverflow.com/questions/16214736/write-data-to-disk-in-python-as-a-background-process and it describes a way to compute and to write pickled data to disk during computations to save memory during multiprocessing. What about separate the issues in the robust detection function so that any function passed to the cacher will just do its work?

**Comment by cpicanco** [comment]
If you are experiencing something similar, I have adapted the cacher function to run in a single process: It is just a workaround while a proper solution is not found:

https://github.com/cpicanco/player_plugins/commit/50e1fdee960bdc0651327211c7c8e9de32b80f07

**Comment by cpicanco** [comment]
@papr and @mkassner, please, any comment will be appreciated.

**Comment by papr** [comment]
Putting background processes back into the main thread is the complete opposite of what we are working on right now. 

We are implementing offline pupil detection and offline calibration at the moment. We are a creating a new, simple, unified way to calculate such stuff in the background, since we cannot process all this in the main thread. I am pretty sure that the Offline Surface Tracker will see a appropriate revision as well with the coming updates. This will hopefully remove your bug.

**Comment by cpicanco** [comment]
Hi @papr , thank you for the feedback. I am aware of the issues related to putting such stuff in the mean thread. Hopefully this new way will come in time!

Best,
Rafael
