### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#705]
Hi,
I'm running the 2d hmd mapper. The CPU usage is always more than 60%. Sometimes it's more than 95%.
Using latest windows bundle 0.9.3.

Is this normal?

System:

    Intel Core i5-6600K @ 3.5 GHz
    RAM 16 GB
    NVIDIA GeForce GTX 970

**Comment by cpicanco** [comment]
Hi, some time ago I was testing the windows bundle and I have found that my windows OS had a lot of hidden services and background tasks. I simple disabled everything I could and performance was improved a lot.

**Comment by mkassner** [comment]
Is this the world process? The hmd 2d mapper is trivial. This should not cost anything in terms of cpu load.

**Comment by PolynomialDivision** [comment]
@mkassner
The world process has a very low cpu usage. Both eye processes together are causing this high cpu usage.

**Comment by papr** [comment]
@PolynomialDivision 
This is expected since the eye processes run the pupil detection algorithm. You can save CPU usage in two ways:

1. Reduce eye camera resolution (You might need to reduce `Pupil min` and `Pupil max` under the `Pupil Detector 2D` in order for it to work.)
2. Reduce the region of interest in which the pupil is searched. (Change the `Mode` in the eye window to `ROI` and resize the ROI to a sensible size.)

**Comment by papr** [comment]
Dear @PolynomialDivision 
were you able to test the suggestions? Did they help? Is this still a problem?

**Comment by papr** [comment]
Stale
