### ISSUE TITLE
glasses-wearers use the eye tracker and some questions about the fixation accuracy 

### ISSUE THREAD

**Issue by gladys0313** [pupil-labs/pupil#724]
Hi all,

   Have you ever asked glasses-wearers to try the eye tracker and how do you think about the gaze fixation accuracy? I tried both on glasses-wearers and contact-lense-wearers. The problem is that in both cases I cannot get a 100% accurate fixation and it is really hard to tell which one is better 

   I'm not sure whether the glasses can make any difference, but from eye camera, it can be seen that sometimes there is reflect light because of the lens. So anyone has experience with that?

   And about the accuracy to fix the gaze, I find it a little bit better if using manual marker calibration than screen marker calibration. But still, sometimes it cannot fix the gaze position accurately and the deviation can be several centimeters (when viewing a A3/A4 size paper). Anyone knows some methods to increase the accuracy? Many thanks!

**Comment by papr** [comment]
Dear @gladys0313 
I wear glasses and have to wear the eye tracking headset for development reasons from time to time. I wear my glasses "above" the headset. This way the eye cameras are not occluded by the glasses. In general, a undistorted view onto the eye (as it is the case contact-lense-weares) will be always more accurate than one where the view is distorted by glasses -- at least for the 3d eye model. An easy way to test if a fixation/gaze/calibration is accurate is to tell the subject to fixate a calibration marker, detect its position in the world image and calculate the euclidean distance between the marker and the gaze points.

Reflecting light can be an issue, yes. Especially, if the reflected light occludes the pupil.

If you re-do a calibration, you will overwrite the previous calibration. Therefore, it does not matter if you do a manual calibration first or not.

Things that you should be aware of when calibrating:
- The pupil needs to be in focus. You can re-focus the eye cameras by turning the small wheel around the lens.
- Make sure that the pupil is detected well, i.e. a red ellipse is visible around the pupil in the eye window and the confidences shown in the top left of the world window are high (consistently >75%)
- The less the headset moves in terms of slippage the better
- It is important that the calibration covers as much of the subject's field of view as possible. The center of FOV is often well calibrated but not the outward part
- Last but not least, make sure the subject really focuses the center of the calibration marker. A good calibration needs a lot of focus. We have some outlier detection but if the calibration data contains multiple saccades, the result will suffer nonetheless.

I hope that this list will help you. Please let us know, if one of the above points helped in particular.

**Comment by gladys0313** [comment]
Dear @papr 

    Thank you very much for your so detailed explanation! Here are some feedbacks:

    1. About _"An easy way to test if a fixation/gaze/calibration is accurate is to tell the subject to fixate a calibration marker, detect its position in the world image and calculate the euclidean distance between the marker and the gaze points."_: The problem is: the yellow point fixing the calibration marker position is always good, but the red point fixing the gaze position is sometimes flying around, although the subject stares at the marker with very high concentration. Does this ever happen to you? Besides, if the distance between the gaze and marker can be calculated, is there anything (probably in some plugins?) we can do to use the distance to compensate the offset? Or the system will know the offset and use this offset to automatically calibrate your gaze when capturing your gaze movement?

     2. I really appreciate your suggestions about (1) re-focus the eye cameras by turning the small wheel (2) confidences >75%. I didn't know them before.

     3. Regarding your fourth and the last suggestions, I also did those before. 

     And thanks a lot for your explanation about the glasses thing. By the way, I am using the high speed world camera + 120HZ monocular eye camera. I know binocular would definitely work better to fix your gaze position, but does high speed world camera also help to some extent?

     Thanks a lot again!

**Comment by papr** [comment]
I know the issue of the jumping pupil/gaze position. This is often the case if pupil detection is bad and has low confidence.

The calibration already tries to fit the mapping such that is as close to the marker as possible. The true mapping is something non-linear and is only approximated. There will be always some kind of error. Additionally, there are physiological limits to the accuracy of the mapping. Even if we know the offset at some point it will be very likely that the offset is different at a different point.

We are currently working on a offline calibration. You will have more control over calibration and mapping accuracy using it. Follow #715 for more information.

Capturing the world view with 120Hz might lead to improved calibration marker detection since there is less motion blur. On the other side, capturing 120Hz content only works with a fairly low resolution which might lead back to a bad calibration marker detection. I would recommend capturing the world view with 60 Hz and a resolution as high as your memory and computational resources allows. Eye videos should be captured with 120Hz. The pupil detection algorithm works well with the low resolution and it allows for a better saccade detection.

Pupil/gaze positions are correlated to world frames. This means that multiple pupil/gaze positions are grouped and assigned to single world frames. The lower the world frame frequency is the more pupil/gaze positions will be grouped together. This is only an issue if you want to record fast moving objects. If the subject looks at a static scene, this is not a problem at all, since the subject's head movement is normally quite low.

**Comment by gladys0313** [comment]
Thank you very much!

What about the resolution of eye videos? You said low resolution, but I have no idea which would be qualified to be called "low", especially to match the 120 HZ frame rate?

**Comment by papr** [comment]
In Pupil Capture, in the Capture Source menu, you can set the recording frequency and resolution. The list of possible values depends on each other. Simply select one and see how the list changes for the other.

**Comment by gladys0313** [comment]
okay, thanks. I'll test with all of your suggestions. Probably in the future I still have questions to ask you...Anyway, thanks a lot!!!

**Comment by papr** [comment]
No problem! I can recommend our [Discord channel](https://discord.gg/c9Dh6Uv) for questions. These Github issues are usually only read by developer. On Discord, you have a better chance to connect with other Pupil users. Good luck with your project!
