### ISSUE TITLE
Windows: Implement audio capture

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#726]
this should be quite simple if ffmpeg supports it on windows.

**Comment by papr** [comment]
Multiple approaches have been tried:

### using libavdevice
Using libavdevice_list_input_source: Does not work on Windows nor on macOS since the AVInputFormats dshow and avfoundation do not implement get_device_list(). The [official issue](https://trac.ffmpeg.org/ticket/4486) is 2 years old and marked as wish/enhancement. dshow requires a fully qualified input name to open the corresponding input. It does not accept indices.

ffmpeg -f dshow -list_devices true -i dummy is able to print all devices but does not use programmatically accessiable APIs for that.

### Using various Python libaries
There are multiple Python bindings (e.g pyaudio) that are able to list all audio devices but do not return the fully qualified name required to initialize a libav stream.

### Enumerate all Windows audio devices using python+ctypes
The following script loads the dsound.dll directly but does also not return the fully qualified name required:
https://gist.github.com/papr/208eb04d7b73ef63607f8ff92c3a34ac

**Comment by drpearcy** [comment]
Just bumping this issue since it's been some time since the last comment. Wanted to know if there had been any headway in getting this up and running. Thanks!

**Comment by papr** [comment]
Implemented in #1110
