### ISSUE TITLE
Running from source : Error in build.py

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pupil#728]
Hi,
this bug is already exisiting for a longer time period.
When u want to run pupil from the source on a windows pc you get this error:

    Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
    Process world:
    Traceback (most recent call last):
      File "C:\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
        self.run()
      File "C:\Python35\lib\multiprocessing\process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\world.py", line 94, in world
        import pupil_detectors
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\pupil_detectors\__init__.py", line 16, in <module>
        build_cpp_extension()
      File "C:\Users\xxx\pupil_windows_fork\pupil_src\capture\pupil_detectors\build.py", line 27, in build_cpp_extension
        shell=True).decode(sys.stdout.encoding)
      File "C:\Python35\lib\subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "C:\Python35\lib\subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command ''C:\Python35\python.exe' setup.py install --install-lib='C:\Users\xxx\pupil_windows_fork\pupil_src\capture'' returned non-zero exit status 1

To fix it just comment out

    ret = sp.check_output(build_cmd.format(quote(sys.executable), quote(install_loc)),
                          shell=True).decode(sys.stdout.encoding)
    logger.debug('Build log:\n{}'.format(ret))

in the build.py files.

**Comment by papr** [comment]
Well, we are aware of this. This is due to `quote()` quoting the path with single quotes. But if you comment these lines out, the pupil detectors won't build. This is not a fix.

A temporal work around is to use the [previous version](https://github.com/pupil-labs/pupil/blob/4b98ac660e626fc672e5f7658c80aee11a89305c/pupil_src/capture/pupil_detectors/build.py).

**Comment by PolynomialDivision** [comment]
@papr : This isn't working for me? Same error.
I forgot to write that you have to run the setup.py scripts on your own and then copy the files to the specific directorys...

**Comment by willpatera** [comment]
@PolynomialDivision the issue here is with Windows paths vs Unix paths. @papr's comment about the temporary workaround is correct.

Also, you do not need to run `setup.py`. You can `run_capture.bat` and all files should build properly. I have tested this on our development environment and can confirm that it is working.

**Comment by mkassner** [comment]
@willpatera  I think @PolynomialDivision  meant that commenting out build lines and manually running setup.py is his workaround. Which is sum is correct.

**Comment by papr** [comment]
@PolynomialDivision @willpatera 
Could you try this patch and confirm that this works on windows?

https://gist.github.com/papr/b6fed7bd17cb82e1963311465215a2fe

**Comment by PolynomialDivision** [comment]
@papr confirmed.

**Comment by papr** [comment]
Great, I will do a PR with the required changes.

**Comment by papr** [comment]
Closed as soon #730 is merged.
