### ISSUE TITLE
Focus is not set on camera

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil#770]
I disabled Autofocus and set the focus manually, which works like a charm.
Then imagine e.g. the camera gets disconnected or the battery of the laptop runs out of power.
When I reconnect the camera (or charge the laptop), the focus of the camera is still displayed in Pupil Capture settings as I set it, however, the camera provides unsharp images. If I slightly move the focus slider, the images from the camera are sharp again.

I suspect that the camera looses it's configuration when it looses power supply.
Wouldn't it be better if Pupil Capture detects when a camera is connected and then updates its configuration? Or maybe it could also send the configuration every few seconds?

Sometimes it's not obvious that the focus is not what I expect it to be and then I easily forget to adjust it.

**Comment by cpicanco** [comment]
Good focus is mandatory for good detection. It should not be forgotten.

Of course, remembering the world focus would be a nice feature to have for *some* applications.

**Comment by pasbi** [comment]
So there is an application where it is better to reset the focus when the camera was disconnected?

**Comment by cpicanco** [comment]
I use the headset with different participants, so "check focus" is an
important item of my own protocol, specially considering the eye camera.
So, for me it does not matter if the setting was saved or not in this case.
However, I use a chin rest to improve overall data quality. Keeping the
same distance from a presentation target with a chin rest reduces the need
for variations in the world focus. In this case saving the setting would be
handy.

Why not autofocus? Because my cameras do not have good autofocus.

On Jul 23, 2017 04:39, "pasbi" <notifications@github.com> wrote:

So there is an application where it is better to reset the focus when the
camera was disconnected?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pupil-labs/pupil/issues/770#issuecomment-317235360>,
or mute
the thread

**Comment by papr** [comment]
Stale. Closing.
