### ISSUE TITLE
No data in diameter history and no recording of the pupil diameter

### ISSUE THREAD

**Issue by PatrycjaPAKS** [pupil-labs/pupil#871]
Hey, 

I'd like to use Pupil Labs to record the pupil diameter in real time and possibly use the online data stream for showing the instant feedback on the recording. I'd like to use the application you're providing - Pupil Capture with diameter history plugin. 

Currently, I can see the and detect the eye as well as the world view. However, I cannot see any data in the diameter histogram in the application. Moreover, recording of the pupil diameter cannot be open in Pupil Player and when I'm opening the .mp4 file, it is either empty (even though there is data theoretically) or it shows a black screen. 

So the question is what do I need to install/open to see the pupil diameter recording? 
How to verify if the diameter history plugin is loaded correctly (if that's the reason for missing data in the feature)? 
And the further question is (a bit off topic in this context), how can I integrate the real-time data from Pupil Capture with some own add-hoc analysis script?

I'm new to Pupil Labs and Python and this is the first time I'm using Pupil Labs for the research purposes.  I would like to use the Pupil Labs in a short demo, where we have 2 weeks for preparation. 

Thank you in advance for the help! :)

Best wishes,
Patrycja Ksiazek

**Comment by papr** [comment]
Hey @PatrycjaPAKS 
Version `0.9.14` only supports the Pupil Diameter History within Pupil Capture. The next version will support it for both, Capture and Player. You will need to open the `Diameter History` plugin. You can do so in the general settings and selecting the plugin in the "Open Plugin..." drop-down menu.

There should appear two new graphs below the confidence graphs in the top left of the world window after loading the plugin. Additionally there should be a `Diameter History` menu at the bottom of the side bar. The next step would be to ensure that you enabled 3d pupil detection. This should be the case by default. If you make a recording, you will need to stop the recording first before opening it in Pupil Player.

Please have a look at these sections of our documentation on how to access pupil data via the realtime newtork interface: https://docs.pupil-labs.com/#development-overview and https://docs.pupil-labs.com/#interprocess-and-network-communication

This is an example script that subscribes to all pupil data: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/filter_messages.py Be aware that at least one eye process needs to be running in order to receive pupil data.

**Comment by PatrycjaPAKS** [comment]
@papr Thank you for a quick reply and the link to real-time data acquisition and data manipulation. It will be very helpful in continuing the research with use of the pupil labs. And speaking of communication with the device - is there an example of how to load the data from the eye tracker directly in MATLAB instead of Python?

In relation to the first paragraph, opening the Diameter History plugin was the thing I initially did. Even though, only the test part of the plugin is visible in the upper left corner but not the graph as it should be. I have however diameter's history plugin in the bottom part of the panel. 

Additionally, I enabled 3d pupil detection both in Pupil Capture and Pupil Service view. And saving recordings before reading them in Pupil Player was also the case.

However, the final output is shown in the screenshot below, where the diameter is still missing. My suspection is then that there is no diameter history becausethe data is simply not (correctly) acquired. I tried to change to the focus and position of the camera, so that the pupil is visible, but it didn't change too much.
[
![diameter_history_empty](https://user-images.githubusercontent.com/30791911/31662624-7a117960-b33f-11e7-808a-181495165f13.PNG)
](url)

**Comment by papr** [comment]
First of all, you seemed to have started the plugin correctly. The world windows should show the video of the scene camera, not the second eye. Enable the `Detect eye 1` switch in the general settings to open the second eye window. You are right though that at least one of the graphs should be displaying data. This is probably a bug and needs to be investigated.

**Comment by PatrycjaPAKS** [comment]
Hey @papr,

I followed your advice to see both the world and eye camera. In fact we are not really interested in the recording of the world for now, so that works as we need. And I can watch both the recording from the world camera and recording of the eye in .mp4 as well as in Pupil Player.

Since diameter history seems to be a bug, do you need more information regarding the problem, so taht you can investigate it better? :)

Best wishes,
Patrycja

**Comment by papr** [comment]
Please understand that there is no Pupil detection within the world window, only in the eye windows. Use the test image input source for World if you do not want to record the scene video.

After inspecting the screen shot a second time, I noticed that the confidence values are not shown either. My guess is that there is a general problem with your setup. Please try the "Restart with default settings" button in the general settings.

**Comment by PatrycjaPAKS** [comment]
Sure I understand it :) 

I restarted with default settings and now I can also see the diameter history. Maybe it was a matter of installing Python libraries/proper environment. I see the general performance is also better now.

Thank you for the help and your time.

Best,
Patrycja
