### ISSUE TITLE
Pupil Player - video export launcher no exported video

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil#893]
Video export launcher creates a file but does not write any data to the file in the current master (https://github.com/pupil-labs/pupil/commit/dc5f1543576a24ead75dd757ceac51d9ce4005e5). Progress indicator in the video export launcher plugin menu GUI does not update.

**Comment by papr** [comment]
@willpatera Which operating systems did you test this on? Did Linux work?

**Comment by papr** [comment]
With [f8ccef5cfea7db79efcedc05fe7fef14c8cc9572](https://github.com/Homebrew/homebrew-core/commit/f8ccef5cfea7db79efcedc05fe7fef14c8cc9572) `opencv` has been migrated from `homebrew/science` to `homebrew/core`. It looks like all brew insta;; options have been removed during the installation:
- [old homebrew/science version](https://github.com/Homebrew/homebrew-science/commit/6c38af15f22ff24e2b398970bc4eb102bfa2b7d2#diff-ebaa128f3fee9eff3ca3d844be60b7fdL18)
- [new homebrew/core version](https://github.com/Homebrew/homebrew-core/blob/f8ccef5cfea7db79efcedc05fe7fef14c8cc9572/Formula/opencv.rb)

This means that the current install instructions for macOS (`brew install opencv3 --with-contrib --with-python3 --with-tbb --without-python`) will ignroe all flags and will install opencv without `tbb`. This leads to a crash when using opencv in the exporter (e.g., the Scan Path plugin uses `cv2.calcOpticalFlowPyrLK`).

A temporary solution is to edit the opencv homebrew formular to use `tbb` and to build opencv instead of pouring the bottled version. The long term solution is to make a pull request to `homebrew/core` and re-introduce the options that we require.

**Comment by mkassner** [comment]
Fixed with our Merged PR to homebrew. Please reinstall OpenCv and test.

**Comment by willpatera** [comment]
This is fixed for me. I am closing this issue now.
