### ISSUE TITLE
Heat Map all Red 

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#96]
Hey guys, I am missing something? 

![2015-03-05-171904_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6513716/d6b4aa2e-c35b-11e4-87c4-735603987a8b.png)

**Comment by willpatera** [comment]
Yes, this is a bug. Looking into it now.

**Comment by willpatera** [comment]
If you specify the `x_scale` and `y_scale` of the surfaces, the heatmap will be displayed. See attached screenshot. 

![screen shot 2015-03-06 at 09 23 04](https://cloud.githubusercontent.com/assets/1407224/6519131/9d306734-c3e2-11e4-90e4-49b17a4727b3.png)

**Comment by cpicanco** [comment]
Thank you Will, I will test it this morning. Please, could you explain the
meaning of this x and y scale? What is the purpose os them?

**Comment by willpatera** [comment]
Hi @cpicanco - `x_scale` and `y_scale` are the *"real world"* scale of the surface. For example, if you used markers at the corners of your laptop screen to define a surface, and your screen is 1280 x 720 pixels, then `x_scale = 1280` and `y_scale = 720`. Or if you have defined a surface that is the scale of an A4 sheet of paper which measures 210 x 297 mm, then `x_scale = 210` and `y_scale = 297`. 

It is important to be able to specify the *"real world"* scale because it gives accurate proportions and allows one to export correctly sized heatmap `.png` files for overlays and for the debugging window. 

Also important because multiple surfaces can be defined with the same set of markers. For example, you might have a set of markers on the edges of your computer screen. As an example, this might define a number of surfaces like: `screen`, `browser window`, `text block`, `sidebar`, etc. Each of these surfaces could be defined by the same markers but would have different *"real world"* size.

**Comment by willpatera** [comment]
I'm going to close this. @cpicanco -- if there is anything further I can reopen.

**Comment by cpicanco** [comment]
So, the measure unit *IS* in pixels, and x_scale, y_scale gives the width, height of the *.png heatmap. I think that it is not behaving as a responsive scale it is behaving like a constant size. Why not call them width and height?

![2015-03-06-150828_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6530820/e46c88fa-c412-11e4-978c-80d82f42c4f2.png)
![2015-03-06-150759_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6530906/a5548a36-c413-11e4-8285-49ce7cc4aa02.png)
![2015-03-06-150733_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6530950/ebec77ec-c413-11e4-8134-166f96d73366.png)
![2015-03-06-150908_1366x768_scrot](https://cloud.githubusercontent.com/assets/6511849/6530951/ebf06f28-c413-11e4-9009-b467f2356b28.png)

**Comment by cpicanco** [comment]
As far as I am understanding the system, the "real" surface size (width, height) in a specific world frame can be inferred from the pixels in the world image. IMO, the default value should be an estimation, in pixels, of the width and height of the surfaces inside a given frame interval. I am assuming, based on this two available variables, that all surfaces are being treated as rectangles. Even the trapezoid surfaces. I don't know what are the plans in terms of "surface" shapes.

**Comment by willpatera** [comment]
@cpicanco, I have made a few quick changes based on your feedback: 
  - Changed `x_scale` and `y_scale` labels to `X size` and `Y size` -- *scale* is misleading -- agreed. Width and height could also be misleading for some users.   
  - Added info text so that users know that they need to press the `(re)-calculate gaze distributions` button and set the `X size` and `Y size` of the surfaces in order to see heatmap visualizations. 

I think your idea of setting an estimated default surface size based on what is observed in the video may lead to better immediate visualizations within player :smile: -- and can be implemented. 

You're right, at current the surfaces are being defined as rectangles, even if trapezoidal. No plans (as of yet) to implement a more generalized polygon surface.  

I'm going to keep this issue closed and migrate to a new `enhancement` issue based on the idea of estimating default surface size values.

**Comment by mkassner** [comment]
A note on shapes other than rectangles:
What we call surfaces are really 2d projections in the scene. You can think of them as coordinate systems in the space. This means that they don't really have any shape. The only thing thats consistent is the coordinate system layout and its scale. We internally represent what the users sees as a `reference_surface` only as a homographic projection with the origin at the bottom left. Anything thats between 0 and 1 in x and y in the surface coordinate system is rendered as the surface. 

For any shape other than a rectangle you need to either use a different coordinate system (polar,ect.) or use a more complex function on top of the already existent coordinate system. But if you use a 2d cartesian coordinate system dealing with rectangles is the easiest and most straightforward. 

As you may have noted we can even compute gaze outside of the surface, this shows that the projection really has no bounds. We just define the bounds at 0 and 1 because for our use case `areas of interest` tend to have boundaries.

A note about scale:
Usually we want to size and compare surfaces with each other. This is where the scaling factor comes into play. For export and visualisation as well as 3d pose estimation we want to know the scale of the reference surface coordinate systems. Thus we scale unit vector coordinate system (0-1) by the `real-world-scale-factor` to give the coordinate system a new unit with a reference to something else we care about (be it the real object size in cm or screen pixels or just a relation to some other unit reference-surface.)

I hope this sheds some light into this topic (and somebody with a real background in these topics could explain it much better.)

**Comment by cpicanco** [comment]
@mkassner, sorry if this a dumb question, but what is the point of making a 2d projection in a scene that is already in 2d (world frames all have only width and height)?

**Comment by mkassner** [comment]
(This may sound corny but no question is ever dumb).

The reference surface is a 2d projection in the scene just like the 2d
image is a projection of the scene. Using homographies
<http://en.wikipedia.org/wiki/Homography_%28computer_vision%29> we can
transform from one space (lets say the projected scene camera image in
pixels) to another space (lets say reference surface 2 that is overlaying
 the cover of a magazine in the scene, units set to be in cm.)

M

**Comment by cpicanco** [comment]
As an educator, I would rather say wise than corny. I could provide you evidence that no question is ever dumb. I could provide you moral reasons as well. But as you certainly know, moral varies a lot! If you mind, I said 'sorry' for something that I was not sorry at all. I was just afraid to ask, possibly because I had an history of punishment (in a technical sense) verbal conditioning. You know... there are a lot of violent people out there.

For instance, this may sound corny but no people is ever lazy.
