### ISSUE TITLE
Calibration freezes Pupil Capture on Mac

### ISSUE THREAD

**Issue by conorrussomanno** [pupil-labs/pupil#973]
I tested:
* v1.1-2 -- Calibration freezes Pupil Capture
* v0.9.14 -- Calibration freezes Pupil Capture
* v0.8.7 -- Calibration works

My computer = 
MacBook Pro (2017)
running Sierra 10.12.5

**Comment by cpicanco** [comment]
Hi, please send the log file, you can found it in pupil_capture_settings.
Also, the traceback would be useful. You will need to run the app from a
terminal window to see if any error is tracedback...

On Dec 5, 2017 17:56, "Conor Russomanno" <notifications@github.com> wrote:

I tested:

   - v1.1-2 -- Calibration freezes Pupil Capture
   - v0.9.14 -- Calibration freezes Pupil Capture
   - v0.8.7 -- Calibration works

My computer =
MacBook Pro (2017)
running Sierra 10.12.5

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pupil-labs/pupil/issues/973>, or mute the thread
