### ISSUE TITLE
Video speeds different

### ISSUE THREAD

**Issue by Gopher-nz** [pupil-labs/pupil#974]
Hi there - not sure if this is an issue or user error on my part.

When I record a session using the eyetracker, I notice that a file world.mp4 is created in the session folder. Now if I open the session using pupil player and export the video the world_viz.mp4 runs at a much slower speed. In comparison. The two videos are:

World.mp4 - Duration 7min; frame size 640x480; Total bitrate 54229kbps; Frame rate 120f/s
World_viz.mp4 - Duration 8min38sec; frame size 640x480; Total bitrate 26721kbps; Fram rate 9727fps

Can someone please explain why this would occur? 

Kind regards, Karl

**Comment by Gopher-nz** [comment]
To top it off the pupil_positions.csv appears to have gathered 8min38sec of eye data - how? I am confused.

**Comment by papr** [comment]
Hey @Gopher-nz 
This is expected behavior. Pupil Capture records videos with a fixed frame rate. This allows Pupil Player to seek frame-by-frame efficiently. We use the `world_timestamps.npy` file to store the true timestamps. During the export the video is encoded with its original frame rate. That the `pupil_positions.csv` data matches the length of the exported video makes sense. 8min38sec is the true length of your recording. Do not worry about the length of the raw recorded `world.mp4` video length. Pupil Player handles the timing for you.

**Comment by Gopher-nz** [comment]
I think I can see my confusion now. The raw video is 7mins, the exported video 8min 38sec, and the video that is played in the pupil player runs at a much slower speed.

This is not a problem when you are extracting pupil labs data but becomes a major issue if you are using the video as reference to extract data from other devices. You are right, the 8min 38sec video is an accurate reflection after comparing the exported video of the simulation we used with the original simulation video file.
